const METRES = window.METRES = {}
const METRES0 = window.METRES0 = {}
const YATIS = window.YATIS = {}

/**
 * 规则韵律(samvṛtta)，四个音步的音节模式相同.
 * 两个诗行(the Line of Verse，短竖线标识)分别含两个音步(pāda，格律单位)
 * @param {string} name 韵律名称
 * @param {string} metre 一个音步的音节模式(syllable pattern)，每个字符为 L、G 或 x
 * @param {number} [yati] 一个诗行在哪个音节处划分音步，即奇数音步的音节数
 * @param {number} [yati2] 一个诗行分为三个音步时指定第二音步的音节数
 */
function AddSamavrtta(name, metre, yati=0, yati2=0) {
  if (metre.indexOf(' ') >= 0) {
    METRES0[name] = [metre, metre]
  }
  metre = metre.replace(/\s/g, '')
  console.assert(!METRES[name], name)
  METRES[name] = metre
  if (yati) {
    YATIS[name] = yati2 ? [yati, yati2] : [yati]
    YATIS[name].push(metre.length - yati - yati2)
  }
}

/**
 * 半规则韵律(ardhasamvṛtta)，奇偶音步各有其音节模式
 * @param {string} name 韵律名称
 * @param {string} metre1 奇数音步的音节模式，每个字符为 L、G 或 x
 * @param {string} metre2 偶数音步的音节模式，每个字符为 L、G 或 x
 */
function AddArdhasamavrtta(name, metre1, metre2) {
  AddVishamavrtta(name, metre1, metre2, '', '')
  if ((metre1 + metre2).indexOf(' ') >= 0) {
    METRES0[name] = [metre1, metre2]
  }
}

/**
 * 不规则韵律，每个音步各有其音节模式
 * @param {string} name 韵律名称
 * @param {string} metre1 第1音步的音节模式，每个字符为 L、G 或 x
 * @param {string} metre2 第2音步的音节模式
 * @param {string} metre3 第3音步的音节模式
 * @param {string} metre4 第4音步的音节模式
 */
function AddVishamavrtta(name, metre1, metre2, metre3, metre4) {
  console.assert(!METRES[name], name)
  metre1 = metre1.replace(/\s/g, '')
  metre2 = metre2.replace(/\s/g, '')
  METRES[name] = metre3 ? [metre1, metre2, metre3.replace(/\s/g, ''), metre4.replace(/\s/g, '')] : [metre1, metre2]
}

AddSamavrtta('1-śaśivadanā', 'LLLLGG')
AddSamavrtta('2-vidyullekhā', 'GGG GGG', 3)
AddArdhasamavrtta('3-anuṣṭubh', 'xxxxLGGx', 'xxxxLGLx')
AddSamavrtta('4-pramāṇikā', 'LGLG LGLG', 4)
AddSamavrtta('8-śālinī', 'GGGG GLGGLGG', 4)
AddSamavrtta('9-rathoddhatā', 'GLGLL LGLGLG', 7) // first: 5
AddSamavrtta('10-svāgatā', 'GLGLLL GLLGG', 6)
AddSamavrtta('13-bhujaṅgaprayāta', 'LGGLGG LGGLGG', 6)
AddSamavrtta('14-toṭaka', 'LLGLLG LLGLLG', 6)
AddSamavrtta('15-sragviṇī', 'GLGGLGGLGGLG')
AddSamavrtta('16-drutavilambita', 'LLLGLLG LLGLG', 7)
AddSamavrtta('17-praharṣiṇī', 'GGG LLLLGLGLGG', 3)
AddSamavrtta('18-vasantatilakā', 'GGLGLLLG LLGLGG', 8)
AddSamavrtta('19-mālinī', 'LLLLLLGG GLGGLGG', 8)
AddSamavrtta('21-śikhariṇī', 'LGGGGG LLLLLGGLLLG', 6)
AddSamavrtta('22-pṛthvī', 'LGLLLGLG LLLGLGGLG', 8)
AddSamavrtta('23-mandākrāntā', 'GGGG LLLLLG GLGGLGG', 4, 6)
AddSamavrtta('26-śārdūlavikrīḍita', 'GGGLLG LGLLLG GGLGGLG', 6, 6)
AddArdhasamavrtta('26-śārdūlavikrīḍitam', 'GGGLLG LGLLLG', 'GGLGGLG')
AddSamavrtta('27-sragdharā', 'GGGGLGG LLLLLLG GLGGLGG', 7, 7)

AddSamavrtta('5-indravajrā',    'GGLGG LLGLGG', 5)
AddSamavrtta('6-upendravajrā',  'LGLGG LLGLGG', 5)
AddSamavrtta('7-upajāti',       'xGLGG LLGLGG', 5)
AddSamavrtta('12-vaṃśastha',    'LGLGG LLGLGLG', 5)
AddSamavrtta('12-indravaṃśa',   'GGLGG LLGLGLG', 5)
AddSamavrtta('12-upajāti',      'xGLGG LLGLGLG', 5)

AddSamavrtta('11-indirā', 'LLLGLG GLGLG', 6)
AddSamavrtta('20-pañcacāmara', 'LGLGLGLG LGLGLGLG', 8)
AddSamavrtta('24-hariṇī', 'LLLLLG GGGG LGLLGLG', 6, 4)
AddSamavrtta('25-kokilaka', 'LLLLGLG LLLGLLGLLG', 7)

// 10/11，第2音步比第1音步多了第4重音节
AddArdhasamavrtta('28-viyoginī',   'LLGLLG LGLG ', 'LLGG LLGLGLG')
// 11/12，śiśulīlā 比 viyoginī 多了末尾的重音节
AddArdhasamavrtta('29-śiśulīlā',   'LLGLLG LGLGG ', 'LLGGL LGLGLGG')

AddArdhasamavrtta('29-śiśulīlā1',  'LLGLLG LGLGG ', 'LLGGL LGLGLG')
AddArdhasamavrtta('29-śiśulīlā2',  'LLGLLL LGLGG ', 'LLGGL LGLGLLG')
AddArdhasamavrtta('29-śiśulīlā3',  'LLLLLL GLGLG ', 'LLLLG LLGLGLG')

AddArdhasamavrtta('30-puṣpitāgrā', 'LLLLLLG  LGLGG', 'LLLLGLLG LGLGG')

/**
 * 给定颂文的一个诗行，计算其韵律(每个音节的轻重)
 * @param {string} text 诗行的IAST文本
 * @param {number} index 音步序号
 * @returns {string} 韵律，由'L'(轻音节)和'G'(重音节)组成
 */
const calcMetre = window.calcMetre = function (text, index) {
  let syllables = Sanscript.splitAksara(text.replace(/▷\d+[a-f]?/g, ''))
  let types = syllables.map(s => Sanscript.getAksaraType(s) + '')

  // 只保留常规音节
  syllables = syllables.filter((s, i) => /[0-6]/.test(types[i]))
  types = types.filter((s, i) => /[0-6]/.test(types[i]))
  const lights = []

  for (let i = 0; i < syllables.length - 1; ++i) {
    // 当前音节如果有元音
    if ('456'.indexOf(types[i]) >= 0) {
      // 双元音，或含随韵、止音，则为重音节
      const vowels = syllables[i].replace(/[^aiuāīūṛṝḷḹáíúeēèoōòṃḥ]/gi, '')
      if (vowels.length > 1 || /[āīūṝḹeēèoōò]/i.test(vowels)) {
        lights[i] = 'G'
      }
      // 单元音后有复辅音，则为重音节
      else if (types[i + 1] === '2' || types[i + 1] === '6') {
        lights[i] = 'G'
      } else { // 其余单元音为轻音节
        lights[i] = 'L'
      }
    } else { // 纯辅音：合并到后面的音节
      syllables[i + 1] = syllables[i] + syllables[i + 1]
      types[i + 1] = Sanscript.getAksaraType(syllables[i + 1])
      syllables.splice(i, 1)
      types.splice(i, 1)
      i -= 2
    }
  }

  // 末音节为纯辅音、倒数第二个音节有元音，则合并为一个音节
  if (syllables.length > 1 && '456'.indexOf(types[types.length - 1]) < 0) {
    syllables[syllables.length - 2] += syllables[syllables.length - 1]
    syllables.splice(syllables.length - 1, 1)
    lights.splice(lights.length - 1, 1)
  }
  if (syllables.length > 1) {
    lights.push('G') // 末音节为重音节
  }

  return lights.join('')
}

const METRES_KV = Object.entries(METRES)
const getMetreTemplate = (i) => METRES_KV[i][1]

/**
 * 匹配一个音步的韵律
 * @param {string} metre 一个音步的韵律，每个字符为L或G
 * @param {string} template 韵律模版，每个字符为 L、G 或 x
 * @returns {boolean}
 */
const matchMetre = (metre, template) => {
  if (template.length !== metre.length) {
    return false
  }
  if (template.indexOf('x') < 0) {
    return template === metre
  }
  let n = template.length
  while (--n >= 0 && (template[n] === 'x' || template[n] === metre[n])) {}
  return n < 0
}

/**
 * 根据一个音步的韵律，查找规则韵律的名称
 * @param {string} metre 一个音步的韵律，每个字符为L或G
 * @returns {string} 韵律名称
 */
const findSamNameByMetre = (metre) => {
  for (let i = 0; i < METRES_KV.length; i++) {
    if (matchMetre(metre, getMetreTemplate(i))) {
      return METRES_KV[i][0]
    }
  }
}

/**
 * 给定各音步的韵律，查找半规则韵律或不规则韵律的名称
 * @param {string[]} metres 各音步的韵律，每个字符为L或G
 * @returns {string} 韵律名称
 */
const findNameByMetres = (metres) => {
  for (let i = 0; i < METRES_KV.length; i++) {
    if (Array.isArray(getMetreTemplate(i))) {
      const m = METRES_KV[i], template = m[1], n = template.length
      if (n === 2) {
        if (matchMetre(metres[0], template[0])
          && matchMetre(metres[1], template[1])) {
          return m[0]
        }
      } else if (n === 4 && metres.length >= 4) {
        const r = template.filter((t, i) => matchMetre(metres[i], t))
        if (r.length > 2) {
          return m[0]
        }
      }
    }
  }
}

const _checkUpajati = (name1, name2, m1, m2) => {
  if (m1 === m2) {
    return m1 && [name1, '']
  }
  if (name1 && name2 && name1 !== name2) {
    if ((name1.indexOf('indravajrā') >= 0 || name1.indexOf('upendravajrā') >= 0)
        && (name2.indexOf('indravajrā') >= 0 || name2.indexOf('upendravajrā') >= 0)) {
      return ['7-upajāti', '']
    }
    if ((name1.indexOf('indravaṃśa') >= 0 || name1.indexOf('vaṃśastha') >= 0)
        && (name2.indexOf('indravaṃśa') >= 0 || name2.indexOf('vaṃśastha') >= 0)) {
      return ['12-upajāti', '']
    }
  }
  const ardha = m1 && findNameByMetres([m1, m2])
  if (ardha) {
    return [ardha, m1.length === m2.length ? '' : '半规则']
  }
}

const hzPuncG = /[\u4e00-\u9fa5\uFF01-\uFF5E\u3000-\u303F()]+/g

/**
 * 给定一个诗节文本，查找其韵律
 * @param {string} text 诗节IAST文本
 * @returns {[]|string[]} [name, type, m1, m2, m3, m4]
 */
window.verseMetre = function(text) {
  // 去除音频标记
  const t1 = (text || '').replace(/(➁\s*)?▷\d+[a-f]?/g, '')
  // 去除行末的 |、||、|number| ，去除连字符、(...)
  const t2 = t1.replace(/\|+(\d[\d.-]*\|+)?\s*$|-|\([^)]+\)/g, '')
    .replace(hzPuncG, '')
  // 拆分为每音步一行，行内有诗行标点就按标点拆行
  const lines = t2.trim().split(/\s*[|\n]+\s*/).filter(s => s)
  if (lines.length < 2) {
    return []
  }

  const metres = lines.map(calcMetre)
  let m1 = metres[0], m2 = metres[1]
  let m3 = metres[2], m4 = metres[3]

  if (lines.length === 2 && (m1.length % 2 === 0 || m2.length % 2 === 0
    || m1.length === m2.length && m1.length > 20)) {
    const n = parseInt((m1.length % 2 === 0 ? m1.length / 2 : m2.length / 2) + '')
    if (Math.abs(m1.length - m2.length) < 2) {
      m4 = m2.substr(n)
      m3 = m2.substr(0, n)
      m2 = m1.substr(n)
      m1 = m1.substr(0, n)
    }
  }
  const ms = m3 && m4 ? [m1, m2, m3, m4] : [m1, m2]
  let name1 = findSamNameByMetre(m1)
  let name2 = findSamNameByMetre(m2)
  let type = ''
  if (!name1 && m1.endsWith('L')) {
    const m_ = m1.substring(0, m1.length - 1) + 'G'
    name1 = findSamNameByMetre(m_)
    if (name1) {
      m1 = m_
    }
  }

  let r = _checkUpajati(name1, name2, m1, m2)
  if (r) {
    return r.concat(ms)
  }
  r = m3 && m4 && _checkUpajati(findSamNameByMetre(m3), findSamNameByMetre(m4), m3, m4)
  if (r) {
    return r.concat(ms)
  }
  if (!name1) {
    name1 = findNameByMetres([m1, m2])
    if (name1) {
      type = m1.length === m2.length ? '' : '半规则'
    } else if (m3) {
      name1 = findNameByMetres(ms);
      if (name1) {
        type = '不规则'
      } else {
        type = m1 === m3 && m2 === m4 ? '半规则' : '不规则'
        return [name1, type].concat(ms)
      }
    }
  }

  return [name1, type].concat(ms)
}

function _yatiMetre(metre, yatis) {
  metre = Array.isArray(metre) ? metre[0] : metre
  metre = metre.replace(/G/g, '长').replace(/L/g, '短')
  let metre2
  if (yatis) {
    const metres = [], m2 = metre.split('')
    yatis.map(y => m2 && metres.push(m2.splice(0, y).join('')))
    metre2 = metres.join(' + ')
    yatis = ' ' + yatis.map(y => y + '').join('+')
  } else {
    const metres = [], m2 = metre.split('')
    for (let i = 0; m2.length; i++) {
      metres.push(m2.splice(0, 3).join(''))
    }
    metre2 = metres.join(' ')
  }
  return {metre, metre2, yatis}
}

/**
 * 得到韵律描述
 * @param {string} name 韵律名称
 * @param {string} m1 第一音步的音节模式
 * @param {string} m2 第二音步的音节模式
 * @returns {string}
 */
window.getYati = function (name, m1, m2) {
  let yatis = YATIS[name] || ''
  let metre = METRES[name] || m1 || ''
  const r = _yatiMetre(metre, yatis)
  if (m2 && m2.length !== r.metre.length) {
    return `（${r.metre.length}/${m2.length}音节）`
  }
  return `（${r.metre.length}音节${r.yatis}）`
}

AddSamavrtta('anīcakam', 'LGLLLLLLLLLG')
AddSamavrtta('līlā', 'LLLLGGLGG')
AddSamavrtta('pratibhādarśanam', 'LLGGLLGGLLLLGG')
AddSamavrtta('karṇapālikā', 'GLGLGGLGLG')
AddSamavrtta('utkaṭapaṭṭikā', 'GGLLGLGLGLGLLLLLLGGLGGLG')
AddSamavrtta('sindhurayā', 'GLLGGG')
AddSamavrtta('vyāyogavatī', 'GGLLGLLLLLLG')
AddSamavrtta('chidram', 'GGLLG')
AddSamavrtta('parimalam', 'LLLLGGLLLLGLLGG')
AddSamavrtta('virāṭ', 'GGGLLGLGLG')
AddSamavrtta('vikuṇṭhakaṇṭhaḥ', 'GLGLGLGLGLGLGLGLGLGLGLGLGG')
AddSamavrtta('vinandinī', 'LLGLLGLLGLLGLG')
AddSamavrtta('rāmābaddham', 'GGGGLLLLGGLLGGLLLLGGLLG')
AddSamavrtta('jaladharamālā', 'GGGGLLLLGGGG')
AddSamavrtta('abhīkam', 'LGGLGGG')
AddSamavrtta('dūrāvalokaḥ', 'GGGGLGGLLLLLLGGGLGGLG')
AddSamavrtta('purohitā', 'LGLGLGG')
AddSamavrtta('prothā', 'GGGLLG')
AddSamavrtta('nakhapadā', 'LLLGLGGG')
AddSamavrtta('pārāvārāntastham', 'GGGGGGGGGLLGGLLLLGGGLLG')
AddSamavrtta('vaḍiśabhedinī', 'LLLGLLLGLG')
AddSamavrtta('karmaṭhaḥ', 'GLLGLLGLLGLLG')
AddSamavrtta('vigāhitageham', 'LLLLLLLLLLGGGGGLLLLGLLGG')
AddSamavrtta('kamalaparam', 'LLLLGGLLLLGGGLLG')
AddArdhasamavrtta('sācīkṛtavadanā', 'LLLLGGGLLGG', 'GGLLLLGLLLLG')
AddSamavrtta('vaṁśottaṁsā', 'GGLLGGLLGGGGGG')
AddSamavrtta('karṇāṭakam', 'GGLGLLLGLGLLLGLGLLLLLLLLLG')
AddSamavrtta('maru', 'LGLGLLLG')
AddArdhasamavrtta('ardharutam', 'GLLLLLLGGLLLG', 'GLLLLLLGLLGLG')
AddSamavrtta('acalapaṅktiḥ', 'GLGLLLLLGG')
AddSamavrtta('vṛndā', 'GGLGLGG')
AddSamavrtta('lalitālabālam', 'LLGLGLLGGGG')
AddSamavrtta('madhumallī', 'LLGGLLGLG')
AddSamavrtta('pratīpavallī', 'LLGLLGGLLGLGLGGG')
AddSamavrtta('nagamahitā', 'LLGGLLGLLLLG')
AddSamavrtta('bhājanaśīlā', 'GGLLGGGLGGLGG')
AddSamavrtta('prabhāvatī', 'GGLGLLLLGLGLG')
AddVishamavrtta('ārdrā', 'LGLGGLLGLGG', 'GGLGGLLGLGG', 'GGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('viṣāṇāśritam', 'LGGLLLGLGGLLLGLGGLLLGLGGLG')
AddSamavrtta('ardhakusumitā', 'GLLLLGLLLLLLG')
AddSamavrtta('bhāsitasaraṇiḥ', 'GLLLLLLLLLLG')
AddSamavrtta('ammethī', 'GGGGLGG')
AddSamavrtta('citrapadā', 'GLLGLLGG')
AddArdhasamavrtta('śālabhañjikā', 'LLGLLLGLGLG', 'GLLGGLGLGLG')
AddSamavrtta('abhrabhramaśīlā', 'GGLLGGLLGGLLG')
AddSamavrtta('haraṇi', 'LLG')
AddSamavrtta('prapātāvatāram', 'LGGLGGGLGLG')
AddSamavrtta('lolatanu', 'LLGGLLG')
AddSamavrtta('aṭṭāsinī', 'GGLGLLGLGLLGG')
AddSamavrtta('darpamālā', 'LGGLGGGLGGLGG')
AddSamavrtta('navasarā', 'GGGLLLG')
AddSamavrtta('bhūriśikhā', 'LLGLLGGGGGGLLG')
AddSamavrtta('dhavalakarī', 'LLLLLLGLLGGG')
AddSamavrtta('atijani', 'GGGGLLLG')
AddSamavrtta('śaralīḍhā', 'LLLLGLLGG')
AddArdhasamavrtta('mārdaṅgī', 'LLGLLLLLGLLLGG', 'GGGLLLLGLLLLLLLLGG')
AddSamavrtta('proñchitā', 'LLGGLGG')
AddSamavrtta('kāhī', 'LLGGGLG')
AddSamavrtta('dvimilā', 'LLGLLGLLGLLGLLGLLGLLGLLG')
AddArdhasamavrtta('aparaprīṇitā', 'LLLLLLLLGGGLGGLG', 'LLLLLLGGLGGLG')
AddSamavrtta('ḍhuṇḍhi', 'LLGGGG')
AddArdhasamavrtta('pramāthinī', 'LLLLGLLGLGLGG', 'LLGGLLGLGLGG')
AddSamavrtta('taralanayanam', 'LLLLLLLLLLLG')
AddSamavrtta('bhramarāvalikā', 'LLGLLGLLGLLGLLG')
AddSamavrtta('mayūrī', 'LGGGLGG')
AddSamavrtta('utpalamālikā', 'GLLGLGLLLGLLGLLGLGLG')
AddSamavrtta('madhupāli', 'LLGLLGLLGLLGLG')
AddSamavrtta('vipulapālikā', 'GLGLGLLLLGLG')
AddSamavrtta('ardhakalā', 'LLGLLGLLG')
AddSamavrtta('modakam', 'GLLGLLGLLGLG')
AddSamavrtta('prasṛmaramarālikā', 'LLLLLGLGLGLG')
AddSamavrtta('viralā', 'LLGLLLLGLGLG')
AddSamavrtta('bālavikrīḍitam', 'GLLLLGLGLLLGLGGLG')
AddArdhasamavrtta('anāsavavāsitā', 'LLGGLLGLGLGLLLGG', 'LLLGLLLGLGLGLGG')
AddSamavrtta('ṛju', 'LGLG')
AddSamavrtta('karālī', 'GGLGGLGG')
AddSamavrtta('meduradantam', 'GLLGLLGLLGLLGLLGLLGLLGLG')
AddSamavrtta('kālambī', 'GGGLGLG')
AddSamavrtta('gotragarīyaḥ', 'GLLGGLLLLGGLLGGLLLLGLLG')
AddSamavrtta('puṭaḥ', 'LLLLLLGGGLGG')
AddSamavrtta('balorjitā', 'LLLLGLGLGLGG')
AddSamavrtta('doṣā', 'GGLLGLG')
AddSamavrtta('anāsādi', 'GLGLGGG')
AddSamavrtta('kośi', 'GLLLLLG')
AddSamavrtta('vārddhi', 'LGLGG')
AddSamavrtta('tuṅgā', 'LLLLLLGG')
AddSamavrtta('kalpalatāpatākinī', 'GGGLLLLLLLLGLLGLGLG')
AddSamavrtta('campakamālā', 'GLLGGGLLGG')
AddSamavrtta('kurarīrutā', 'LLLLGLGLLLGLLG')
AddArdhasamavrtta('śiśumukhī', 'LLLGLLLGLLGLG', 'LLLGLLLLGLGLG')
AddSamavrtta('atimohā', 'LLGGLLGG')
AddSamavrtta('gaganodgatā', 'GLGLLLGLGLLGLG')
AddSamavrtta('ākatanu', 'LGLGGLLG')
AddSamavrtta('pravāhikā', 'LGLGGLGGLGGLG')
AddSamavrtta('arajaskā', 'LGLLGG')
AddSamavrtta('unnālam', 'GGLLLLLLGG')
AddSamavrtta('bahulābhram', 'LLGGLLLLGGLLGGG')
AddSamavrtta('vikatthanam', 'LGLLGLLLGLLG')
AddArdhasamavrtta('karṇinī', 'GLGLLLGLLGG', 'GLGLLLGLGLG')
AddVishamavrtta('vaidhātrī', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG')
AddSamavrtta('vaiśvadevī', 'GGGGGGLGGLGG')
AddSamavrtta('śaṅkhadyuti', 'LLGGLG')
AddArdhasamavrtta('pramodapariṇītā', 'LLLLLLGLGLGLGG', 'LLLLGLLGLGLLLGG')
AddSamavrtta('kuhī', 'LGLLLG')
AddSamavrtta('niṣadham', 'GLLGLGLLG')
AddSamavrtta('sopadhi', 'GLGGLG')
AddArdhasamavrtta('saṁpātaśīlā', 'GGLGGGGLGG', 'LLGLLLGGGLGG')
AddSamavrtta('varīyaḥ', 'LGGLG')
AddSamavrtta('kīralekhā', 'LLLGLGLLLGLGG')
AddArdhasamavrtta('prabhāsitā', 'GGGLLGLGLG', 'LLGLLGLGLG')
AddSamavrtta('samit', 'LLLLGGLLLLG')
AddSamavrtta('kīlālam', 'GLLGGGGGLG')
AddSamavrtta('pravaralalitam', 'LGGGGGLLLLLGGLGG')
AddSamavrtta('vīraṇamālā', 'GLLGGLLLLLLG')
AddSamavrtta('anindagurvinduḥ', 'LLLLGGGGLGLGGG')
AddSamavrtta('varivaśitā', 'LLGLLGLLLLLLG')
AddSamavrtta('vinidrasindhuraḥ', 'GLGGLGGLGGLGLGLGLGLGLGLGLG')
AddSamavrtta('lalitā', 'GGLGLLLGLGLG')
AddSamavrtta('phulladāma', 'GGGGGLLLLLLGGLGGLGG')
AddSamavrtta('aprītā', 'LLLGGGLG')
AddSamavrtta('dhaureyam', 'GLLGLLLLGLLGLLLLLLLLGGGG')
AddSamavrtta('mantrikā', 'GLGGGG')
AddSamavrtta('kalpāhārī', 'LLLLLLLLLLLLGGGG')
AddSamavrtta('bhujagahāriṇī', 'LLLGLGLLGLG')
AddSamavrtta('śiprā', 'GGGGGGG')
AddSamavrtta('hindīram', 'GGGGGLG')
AddSamavrtta('śukavanitā', 'LLGLLGGLLGLLLLLLG')
AddSamavrtta('māyāvinī', 'LLGGGLG')
AddSamavrtta('mattakokilam', 'GLGLLGLGLLGLGLLGLG')
AddSamavrtta('puṣpaśakaṭikā', 'GLLLLGGGLGGLGG')
AddSamavrtta('kuberakaṭikā', 'LLGLLGLGLLLGG')
AddSamavrtta('narāvaliḥ', 'GGLGLLLLLLLLG')
AddSamavrtta('vaṁśapatrapatitam', 'GLLGLGLLLGLLLLLLG')
AddSamavrtta('narī', 'LGGLG')
AddSamavrtta('śarakāṇḍaprakāṇḍam', 'LLGGLGLLLGLGGLGGLGGLG')
AddSamavrtta('nandathu', 'GLLLGGG')
AddSamavrtta('karṇalatā', 'LLGGLLGLLLLGLLG')
AddSamavrtta('kanakamañjarī', 'LLLGLGGLGLG')
AddSamavrtta('ṛcā', 'LGLLGGG')
AddSamavrtta('mattamayūraḥ', 'GGGGGLLGGLLGG')
AddSamavrtta('guṇasārikā', 'LGLLGLLGLLGLG')
AddSamavrtta('saurabhaśobhāsāraḥ', 'GLLGGGGGLLLLLLGLLLLG')
AddSamavrtta('kaṭhinī', 'LLLLLGLGLGGLG')
AddSamavrtta('ūhinī', 'GLGLLGLGGLGLLGG')
AddVishamavrtta('māyā', 'LGLGGLLGLGG', 'LGLGGLLGLGG', 'LGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('vātormī', 'GGGGLLGGLGG')
AddSamavrtta('nīranidhiḥ', 'LLLGGLLLLG')
AddSamavrtta('madhu', 'LG')
AddArdhasamavrtta('sundarī', 'LLGGLLGLGLG', 'LLGLLGLGLG')
AddSamavrtta('samānikā', 'GLGLGLGG')
AddSamavrtta('gṛhiṇī', 'LLGGGGG')
AddSamavrtta('vandāruḥ', 'GGGLLGGLG')
AddSamavrtta('ardhāntarālāpi', 'GGLGGLGGLGGLGGLGGG')
AddArdhasamavrtta('kamalākarā', 'GLLGLLGLLGG', 'GLLLLLLGLLGG')
AddSamavrtta('bhujaṅgī', 'LGGLGGLGGLG')
AddSamavrtta('bhastrānistaraṇam', 'GGGLLGGLLLLLLGLGLGLLGG')
AddSamavrtta('indravimānam', 'GLLGGLLLLGGGGLLLLLLLLGG')
AddSamavrtta('drutapadam', 'LLLGLLLGLLGG')
AddSamavrtta('cakitā', 'GLLLLGGGGGGLLLLG')
AddSamavrtta('suvanamālikā', 'GGLLLGLGLLLG')
AddSamavrtta('vajrālī', 'GGLLGGGGGGGGGGG')
AddArdhasamavrtta('kalanā', 'LLGLGLLLGLLGG', 'LLGLGLLLGLGLG')
AddSamavrtta('bhāsamānabimbam', 'GLGLGLGLLLLGLGLGLLLLGLGG')
AddSamavrtta('ayanapatākā', 'GGGLLLGGG')
AddSamavrtta('haripadam', 'LLLLLLLG')
AddSamavrtta('candravartma', 'GLGLLLGLLLLG')
AddSamavrtta('bhasalamadam', 'GLLLLGLGLGGLG')
AddSamavrtta('mihirā', 'LLLLLGLGGLGG')
AddSamavrtta('hīralambi', 'GLLGLLGLGG')
AddSamavrtta('dolā', 'LLGG')
AddSamavrtta('vidalā', 'LLLLLGGGLGLLG')
AddSamavrtta('mukulitakalikāvalī', 'GLGLLLLLLGLG')
AddArdhasamavrtta('atiprativinītā', 'LLGGLLGLGLLLGG', 'LLLLGGLGLGLGG')
AddSamavrtta('lalitapatākā', 'LLLLLGLGGLGGGG')
AddSamavrtta('tilakā', 'LLGLLG')
AddSamavrtta('cūḍāpīḍam', 'GGGGLLLLLLGGGG')
AddSamavrtta('drutamukham', 'LLLLLLLLLLLLGGGGLGLGGG')
AddSamavrtta('kulacāri', 'LGLGLLGG')
AddSamavrtta('varhāturā', 'GGLGLLGGLG')
AddSamavrtta('sākṣī', 'LLGLLGLGLGGG')
AddSamavrtta('manoramā', 'LLLGLGLGLG')
AddSamavrtta('rodhakam', 'LLLGLLGLLGG')
AddSamavrtta('hāṭakaśāli', 'GGLLGG')
AddSamavrtta('dantālikā', 'GGLGGGGLGGGGLGGG')
AddSamavrtta('mañjubhāṣiṇī', 'LLGLGLLLGLGLG')
AddSamavrtta('jāhamukhī', 'GLLGLLGLLGLLGG')
AddSamavrtta('nemadhāri', 'LGLGLLGLGG')
AddSamavrtta('madanajavanikā', 'LLLLGGLLLLLLG')
AddSamavrtta('niravadhigatiḥ', 'LLLLLGGLLLG')
AddSamavrtta('kṛtakatikā', 'LLLLLLLLLLLG')
AddSamavrtta('ṭaṅkaṇam', 'GLGLLLGLGLLLGLGLLLG')
AddSamavrtta('dhūmrālī', 'LGGLGGGGGG')
AddSamavrtta('maṇḍalam', 'GLLLG')
AddSamavrtta('sainikam', 'LGLGLGLGLGG')
AddSamavrtta('madanamālikā', 'LLLGLGLLLGLGGLG')
AddSamavrtta('vidhuravirahitā', 'LLGGGLLGGGLLLLLLG')
AddSamavrtta('upadārikā', 'GLGLGLLLGLG')
AddSamavrtta('badhirā', 'LLGGLLGLGLGG')
AddArdhasamavrtta('hariluptā', 'LLGLLGLLGLG', 'LLGGLLGLLGLG')
AddArdhasamavrtta('viyadvāṇī', 'LLGGLLGLGLGG', 'GGGLLGLGLGGG')
AddArdhasamavrtta('aparavaktram', 'LLLLLLGLGLG', 'LLLLGLLGLGLG')
AddArdhasamavrtta('avahitrā', 'GLLGLLGLLGG', 'LLGLLGLLGLG')
AddSamavrtta('gaganagatikā', 'GLGLLGLGLLLLLG')
AddSamavrtta('amṛtagatiḥ', 'LLLLGLLLLG')
AddSamavrtta('tantrī', 'GGGLGG')
AddSamavrtta('kalahetikā', 'LLGLGLLGLGLLLG')
AddSamavrtta('valabhī', 'GLLGLLGLGLGG')
AddArdhasamavrtta('ketumatī', 'LLGLGLLLGG', 'GLLGLGLLLGG')
AddArdhasamavrtta('kinnaṭakaḥ', 'GGLLGLLGLLG', 'LLGLLGLLGLLG')
AddSamavrtta('makaramukhī', 'LLLLLLLLLG')
AddSamavrtta('mukhalā', 'LLLLGGLLG')
AddSamavrtta('atiśāyinī', 'LLGLLGLGLGLLLGLGG')
AddSamavrtta('karamālā', 'LLGGLLGGLLGG')
AddSamavrtta('mahodhikā', 'LGLGLLG')
AddSamavrtta('bhrūḥ', 'LGGGG')
AddSamavrtta('upadhāyyā', 'GLLLLLLLGG')
AddSamavrtta('balākā', 'LGG')
AddSamavrtta('vilambalalitam', 'LGLLLGLGLLLGLGLLLGLGLLG')
AddSamavrtta('virudarutam', 'GGGGLLLLGGLLGGLLG')
AddSamavrtta('vāsantī', 'GGGGGLLLLGGGGG')
AddSamavrtta('viraloddhatā', 'GGGLLGLGLLLG')
AddSamavrtta('jatu', 'LLGLG')
AddArdhasamavrtta('naṭakaḥ', 'LLGLLGLLGLLG', 'GGLLGLLGLLG')
AddSamavrtta('śalabhalolā', 'LGGLGGLGLLLGG')
AddSamavrtta('ṣaṭpaderitam', 'LLLGLGLLLGLGLLLGLG')
AddSamavrtta('alakālikā', 'GGLGLLGLGLLGLG')
AddSamavrtta('rūpāmālī', 'GGGGGGGGG')
AddArdhasamavrtta('vimāninī', 'GGGLLLLGLGLG', 'LLGGLLGLGLG')
AddSamavrtta('pathikāntā', 'GLLLLLLGLLGG')
AddSamavrtta('śramitaśikhaṇḍī', 'GLLLLGGLLGG')
AddSamavrtta('pramodatilakā', 'GGLGLLLGLLGLG')
AddArdhasamavrtta('karīritā', 'LLGGLLLGLGLG', 'LLGLLGLGLG')
AddSamavrtta('śāradacandraḥ', 'GGLLGGLLGGLLGG')
AddSamavrtta('svarṇābharaṇam', 'LLGLLGLLGLLGLLLLGGGLLG')
AddSamavrtta('somaśruti', 'LGGGLG')
AddSamavrtta('kroḍakrīḍam', 'GGGGLLLLLLLLGLGGLG')
AddSamavrtta('naraśikhī', 'LLLGLLLGLLLGLLLG')
AddSamavrtta('nīlagirikā', 'GLLLGLLLGLLG')
AddSamavrtta('amitanagānikā', 'GLLLLGLGLLGLG')
AddArdhasamavrtta('upacitrā', 'LLGLLGLLGLG', 'GLLGLLGLLGG')
AddSamavrtta('bhārākrāntā', 'GGGGLLLLLGLGLLGLG')
AddSamavrtta('kupyam', 'GLLLLGLGLG')
AddArdhasamavrtta('ahīnatālī', 'GGGLLLLGLGLG', 'LLGGLLLLGLGLGLGG')
AddSamavrtta('vasanaviśālā', 'LLLLLLLGGGGG')
AddSamavrtta('kalahaṁsaḥ', 'LLGLGLLLGLLGG')
AddSamavrtta('pṛṣadvatī', 'GGLGLGGLGLGLG')
AddSamavrtta('nirvādhikā', 'GGLGLLG')
AddSamavrtta('anavīrā', 'LLGGLLLLG')
AddSamavrtta('vipulāyitam', 'GGGLLLLGLGLLLLLLGLGLGLG')
AddSamavrtta('ativāsitā', 'LLGLGGGLGLLG')
AddSamavrtta('kṛtayuḥ', 'LLLLLLLG')
AddSamavrtta('arditapādam', 'GLGLLLLGLLGG')
AddSamavrtta('veśi', 'GLLLLLLG')
AddSamavrtta('rañjakam', 'GLLLLGLLG')
AddSamavrtta('tāvuri', 'GGLG')
AddSamavrtta('digīśaḥ', 'LLGLGLGG')
AddSamavrtta('vāṇinī', 'LLLLGLGLLLGLGLGG')
AddSamavrtta('kiṇapā', 'GLLLGGG')
AddSamavrtta('viśakalitā', 'GGGGLLLLGGLLLLG')
AddSamavrtta('sukarṇapūram', 'LLLGLGLGLGLGG')
AddSamavrtta('ānanamūlam', 'GLLGGLLGGLLGG')
AddSamavrtta('alakā', 'LLLLLLLLLLLLLLLLLLLLLLLLG')
AddSamavrtta('kurarikā', 'LLLGLGGG')
AddSamavrtta('aśokānokaham', 'GGGGLLLLLGLLLLLGLGGGLGGLGG')
AddSamavrtta('yamanakam', 'LLGLLLG')
AddSamavrtta('īdṛṣam', 'GLGLGLGLGLGLGLGLGLGG')
AddVishamavrtta('ratākhyānakī', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG')
AddSamavrtta('udarkaracitā', 'LLGLLGLGLLLG')
AddSamavrtta('alolā', 'GGGLLGGGGGLLGG')
AddSamavrtta('parilekhaḥ', 'LGLLGLLGLLGG')
AddSamavrtta('javanaśālinī', 'LLGLLGLGGLG')
AddSamavrtta('vasantahāsaḥ', 'GGGGLLLLGLGG')
AddSamavrtta('karmadā', 'GLGLLG')
AddSamavrtta('sīdhuḥ', 'LLGGLLGLGLG')
AddSamavrtta('cayanam', 'LGGLLLLG')
AddArdhasamavrtta('hariṇīplutā', 'LLLGLLGLLGLG', 'LLGLLGLLGLG')
AddSamavrtta('gallakam', 'LLLLLLLGGLG')
AddSamavrtta('viṣṭambhaḥ', 'LLGLLGLLGGG')
AddSamavrtta('prabhadrakam', 'LLLLGLGLLLGLGLG')
AddSamavrtta('śambūkaḥ', 'LLGGGGG')
AddSamavrtta('vāriśālā', 'LGLGGLGG')
AddSamavrtta('anu', 'LLLLGGG')
AddSamavrtta('arbhakamālā', 'GLLGGLLLLGGLLLLGGGLLGG')
AddSamavrtta('śallakaplutam', 'LLGGLGLG')
AddArdhasamavrtta('asurāḍhyā', 'GGGLLGLGLGG', 'LLLLLLGLGLGG')
AddSamavrtta('rucivarṇā', 'LGLLLGLGLLLGG')
AddSamavrtta('antarvanitā', 'GGGLLGGGGGG')
AddSamavrtta('kalamatallikā', 'LLLGLGLLLGLGLLLGLGGLG')
AddSamavrtta('hali', 'LLLLG')
AddSamavrtta('bhujaṅgasaṅgatā', 'LLGLGLGLG')
AddSamavrtta('vāridhiyānam', 'GLLGGLLGG')
AddSamavrtta('praharaṇakalikā', 'LLLLLLGLLLLLLG')
AddArdhasamavrtta('vimukhī', 'LLLLLLGLLLLGG', 'LLLLLLLLGLLGG')
AddSamavrtta('haṭhinī', 'GGGLGLLG')
AddSamavrtta('maulisrak', 'GGGLLGG')
AddSamavrtta('kalādharaḥ', 'GLGGLGLGLGLGLG')
AddSamavrtta('vaṁśalaḥ', 'GLLGGLLGLLGLLGLLG')
AddSamavrtta('pāṁśu', 'LLLGG')
AddSamavrtta('sandhyā', 'GGLLLLGG')
AddSamavrtta('sāmapadā', 'GGGLLGLLLLG')
AddSamavrtta('amaracamarī', 'LLLLLLLLLLLLLLLLLLLLLLG')
AddSamavrtta('halamukhī', 'GLGLLLLLG')
AddSamavrtta('pāli', 'LLGGG')
AddSamavrtta('saṁśrayaśrīḥ', 'GGLGGLGGLGG')
AddSamavrtta('lalitam', 'LLLLLLGGGGLG')
AddSamavrtta('paṅkajadhāriṇī', 'GGGLLGLGLLLGG')
AddSamavrtta('padmāvarttaḥ', 'GGGGGGGGGG')
AddSamavrtta('paridhārā', 'LLGGLGGG')
AddSamavrtta('ulapā', 'GLLLLLG')
AddSamavrtta('pārṣatasaraṇam', 'GLLLLLLGGGGGLLLLLLLLLLGG')
AddSamavrtta('upavali', 'LLLLLG')
AddSamavrtta('ākekaram', 'GGLLLLLLG')
AddSamavrtta('viṭ', 'GLLGG')
AddSamavrtta('jananidhivelā', 'LLLLGGLLGGGGLLG')
AddSamavrtta('candrāpīḍam', 'GGGGGGGGGGGGGGGG')
AddSamavrtta('adritanayā', 'LLLLGLGLLLGLGLLLGLGLLLG')
AddArdhasamavrtta('amarāvatī', 'LGLGLGLGLGLGG', 'GLGLGLGLGLGG')
AddSamavrtta('kalāpadīpakam', 'GLGLGLGLGLGLGLGLGLG')
AddSamavrtta('vīravimānam', 'GLLGLLGLLGLLGLLGLLGG')
AddArdhasamavrtta('viparītākhyānakī', 'LGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('kṣaram', 'LGLLLLLG')
AddArdhasamavrtta('aruntudaḥ', 'LLGLLGLGLG', 'LLLLGLLGLGLG')
AddSamavrtta('śaśikarī', 'LLGLLLGGG')
AddSamavrtta('culakam', 'LLLLLLLLG')
AddSamavrtta('kṛkapādi', 'LLLGLGLLGG')
AddSamavrtta('kṣupam', 'LGLLG')
AddSamavrtta('sammadamālikā', 'LLLLLGLLGLG')
AddArdhasamavrtta('padmāvatī', 'LLGLGLLLGLLGG', 'GGLGLLLGLLGG')
AddSamavrtta('sari', 'LLLLLG')
AddSamavrtta('nīrohā', 'LLGGLGGGGG')
AddSamavrtta('valivadanam', 'LLLLGGGGGGLLLLGG')
AddVishamavrtta('kumārī', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG')
AddSamavrtta('garudavāritā', 'LGLLLGLGLLGLG')
AddArdhasamavrtta('drutamadhyā', 'GLLGLLGLLGG', 'LLLLGLLGLLGG')
AddSamavrtta('jīmūtadhvānam', 'GGGGGGGGGGGGGGGGGGGGGGGGGG')
AddSamavrtta('kaladhautapadam', 'LLGLLGLLGLLGLLGG')
AddSamavrtta('ciraruciḥ', 'LGGLLLG')
AddSamavrtta('satketuḥ', 'GGGLLLLLLLGLGLGLGG')
AddSamavrtta('aniloddhatamukhī', 'LLLGLGGLGLLLG')
AddSamavrtta('sitastavakaḥ', 'GGLGLLLGGLGLLLGGLGLLLG')
AddSamavrtta('ṛtam', 'LLLLLLLLGG')
AddSamavrtta('agarim', 'LLLLLLLLLLG')
AddSamavrtta('nayamālinī', 'LLLLGLGLLLGG')
AddSamavrtta('mālyopastham', 'LLLLLLLLLLGGGGGG')
AddArdhasamavrtta('asudhā', 'LLGGLLGLGLG', 'GGGLLGLGLG')
AddSamavrtta('kalaham', 'LLGGLLGGG')
AddSamavrtta('priyā', 'LLGLG')
AddSamavrtta('pikālikā', 'GLLLGLLGLGLG')
AddSamavrtta('dvāravahā', 'GLGGGLLGGG')
AddSamavrtta('vidyā', 'GGLLGLLG')
AddSamavrtta('līḍhālarkaḥ', 'GGGGGLLLGLGG')
AddSamavrtta('viśvavirāṭ', 'GGGLLGLGLGG')
AddSamavrtta('māṇḍavakam', 'LLLGGLLG')
AddSamavrtta('karmiṣṭhā', 'GLLLLGGGG')
AddSamavrtta('suvihitā', 'LGGLLGLGLLLG')
AddVishamavrtta('varddhamānam', 'GGGLLGLGLGLLGG', 'LLGLLLLGLGLGG', 'LLLLLLLLGLLLLLLLLG', 'LLLLLLLLLLGLLGG')
AddSamavrtta('prākārabandhaḥ', 'GGLGGLGGLGG')
AddSamavrtta('śīrśavirahitā', 'GGLLGGGLLGLLLLG')
AddSamavrtta('ūpikam', 'LGGGGLG')
AddSamavrtta('kaṅkaṇakvāṇaḥ', 'GLGGLGGLGGLGGLGGLGGLGG')
AddSamavrtta('ānatā', 'GGGLLLGLGGLGG')
AddSamavrtta('titikṣā', 'GLLLLLLGGLLLLLLGG')
AddVishamavrtta('manahāsā', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG')
AddSamavrtta('kalali', 'LLLGG')
AddSamavrtta('tumulakam', 'LLLLLLLLLLLLLLLLLG')
AddSamavrtta('upacitaratikā', 'GLLLLLLGLLGLG')
AddSamavrtta('vṛtumukhī', 'LLLGLLGG')
AddSamavrtta('udaraśri', 'LLGLLGGGG')
AddSamavrtta('sugandhiḥ', 'LLGLLLLGG')
AddSamavrtta('taravārikā', 'LLLLLGLLGLGLLGLG')
AddSamavrtta('mṛgī', 'GLG')
AddArdhasamavrtta('anaṅgapadam', 'GLLGLLGLLGLLG', 'LLGLLGLLGLLGG')
AddSamavrtta('sāraṅgaḥ', 'GGLGGLGGLGGG')
AddVishamavrtta('śaṅkhacūḍā', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG')
AddSamavrtta('khelāḍhyam', 'GGGLLGGGG')
AddSamavrtta('kṛtamaṇitā', 'GLLLLLLLLG')
AddSamavrtta('harikāntā', 'LLGGLLGGLLG')
AddSamavrtta('anilohā', 'LLGGLLGGLLGGLLGG')
AddSamavrtta('sārāvanadā', 'GGLLGLGG')
AddSamavrtta('śarahatiḥ', 'LLLLLLLLLLLLLLG')
AddSamavrtta('prabodhaphalitā', 'GLGLLLGLGLLLG')
AddSamavrtta('vāsaki', 'LLLLGLG')
AddSamavrtta('plavaṅgamaḥ', 'GLLGLLGGLGLLGLG')
AddSamavrtta('narācaḥ', 'LGLGLGLGLGLGLGLG')
AddSamavrtta('mālatī', 'LLLLGLLGLGLG')
AddSamavrtta('kandaḥ', 'LGGLGGLGGLGGG')
AddSamavrtta('puraṭi', 'LLLLGLG')
AddSamavrtta('anṛtanarma', 'LLGGLLGG')
AddSamavrtta('aśokalokaḥ', 'GGGGGGGGGGGGGGLGLGGGG')
AddSamavrtta('mahimāvasāyi', 'LLGGLLGLGG')
AddArdhasamavrtta('akusumacaram', 'GLLLLLLGLLGG', 'GLLGLLGLLGG')
AddSamavrtta('bhīmāvarttaḥ', 'GGGGLLLLLLLLLLGG')
AddSamavrtta('karapallavodgatā', 'LGGLGGLLGLGLG')
AddSamavrtta('pārāntacārī', 'LGGGGLGG')
AddSamavrtta('cāru', 'GG')
AddSamavrtta('karṇiśaraḥ', 'GLLGLLGLLGGLLG')
AddSamavrtta('paripuṅkhitā', 'GLGLLGLGLGLG')
AddSamavrtta('madhumatī', 'LLLLLLG')
AddSamavrtta('citrā', 'GGGGGGGGGLGGLGG')
AddSamavrtta('vipinatilakam', 'LLLLLGLLLGLGGLG')
AddSamavrtta('jagatsamānikā', 'LLGLLGLGLGLGG')
AddSamavrtta('induvaṁśā', 'GGLGGLLGLGLG')
AddSamavrtta('kalpakāntā', 'GLGGGLGGLGGLGG')
AddArdhasamavrtta('nirmadhuvāri', 'GGLGLLGLGLLGG', 'LLGLGLLLGLGLG')
AddSamavrtta('jarā', 'LGLLGLLGLG')
AddSamavrtta('bhinnapadam', 'GLLGLLLGLG')
AddSamavrtta('varṇabalākā', 'LLGLLGGLLGG')
AddSamavrtta('sindhusauvīram', 'GLGGLGGLGGLGGLGGLG')
AddArdhasamavrtta('paravaktram', 'LLLLGLLGLGLG', 'LLLLLLGLGLG')
AddSamavrtta('nāgāri', 'LLGLGGGG')
AddArdhasamavrtta('śiśirā', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG')
AddSamavrtta('saurabhavarddhinī', 'LLLLGGLLGLG')
AddSamavrtta('maṅkuram', 'GGGLGG')
AddArdhasamavrtta('ketuḥ', 'GLLGLGLLLGG', 'LLGLGLLLGG')
AddSamavrtta('prasṛmarakarā', 'LLLLLGLGGLG')
AddSamavrtta('kaṭhodgatā', 'LLGLGLG')
AddSamavrtta('ahari', 'LLLLLGG')
AddSamavrtta('ujjhitakadanam', 'GLLLLLLGLLGLLGLLLLLLLLLLGG')
AddSamavrtta('kuraṅgāvatāraḥ', 'LGGLGGLLGLLG')
AddSamavrtta('niṣkalakaṇṭhī', 'GLLGGGLLGGGLLGGLLGGLLG')
AddArdhasamavrtta('prativinītā', 'LLLLGGLGLGLGG', 'LLGGLLGLGLLLGG')
AddSamavrtta('krīḍacandram', 'LGGLGGLGGLGGLGGLGG')
AddArdhasamavrtta('avācīkṛtavadanā', 'GGLLLLGLLLLG', 'LLLLGGGLLGG')
AddSamavrtta('arāli', 'LGLLGLLG')
AddSamavrtta('kiṣku', 'GGLGGLGG')
AddSamavrtta('kalavallivihaṅgaḥ', 'LGLGGLLGGLGG')
AddSamavrtta('gopāvedī', 'LLLGGGGG')
AddSamavrtta('kirmīram', 'GGGGLGG')
AddSamavrtta('viśalyam', 'LGGLGGLGG')
AddSamavrtta('śambaram', 'LLLGLLGLLGLGLLLGLLGLLGLG')
AddSamavrtta('varaśaśi', 'GLGLLLG')
AddSamavrtta('kalilā', 'LLGLLGLG')
AddSamavrtta('avandhyopacāraḥ', 'LGGLGGLGGLGGLGGLGGLG')
AddSamavrtta('kākalīkalakokilaḥ', 'GLGLLGLGLLGLGLLGLGLLGLGLLG')
AddSamavrtta('paṅkāvaliḥ', 'GLLLLLLGGLLLG')
AddArdhasamavrtta('vaiyālī', 'LLLLLLGLGLG', 'GGGLLGLGLG')
AddSamavrtta('ibhabhrāntā', 'GGGLGGG')
AddSamavrtta('mithunamālī', 'LLLLLLGGGGGG')
AddSamavrtta('upakārikā', 'LLGLGLLGLGLLGG')
AddSamavrtta('kusumitalatāvellitā', 'GGGGGLLLLLGGLGGLGG')
AddSamavrtta('upasarasī', 'LLGLLLLGLLLLG')
AddSamavrtta('cakram', 'GLLLLLLLLLLLLG')
AddSamavrtta('ahiṁsā', 'GLGLGGG')
AddSamavrtta('arkaśeṣā', 'GLGLGLGLGLGLGG')
AddSamavrtta('narhi', 'LGGLGGG')
AddSamavrtta('cārucāraṇam', 'GLGLLLLLGG')
AddSamavrtta('pratardi', 'LGLGLGG')
AddSamavrtta('kheṭakam', 'GLLLGLGGLG')
AddSamavrtta('godhi', 'LLGLLGG')
AddSamavrtta('mānākrāntā', 'GGGGGGGGGGGGGGGGG')
AddArdhasamavrtta('vāsavavanditā', 'GGGLLGLGLG', 'GGLLGLGLG')
AddSamavrtta('vaṁśastham', 'LGLGGLLGLGLG')
AddSamavrtta('bhujagaśiśubhṛtā', 'LLLLLLGGG')
AddSamavrtta('panthā', 'LGGGGG')
AddSamavrtta('amarandi', 'GGLGLLGG')
AddSamavrtta('parīvāhaḥ', 'LLLGGLGGLGGLGG')
AddSamavrtta('mālāvalayam', 'GGGGLLLLGGLLLLGG')
AddSamavrtta('aviralaratikā', 'GLLLLLLGLGLG')
AddSamavrtta('vīrā', 'GGGGLLLLG')
AddSamavrtta('kaḍāram', 'LGGLLLLGGGG')
AddSamavrtta('troṭakam', 'LLLLGLGLGGLLGLLG')
AddSamavrtta('adhikārī', 'LLGGLLG')
AddSamavrtta('ayamānam', 'LLGLLGLLGLLGLLGLLGLLGG')
AddSamavrtta('satī', 'LLLG')
AddSamavrtta('atulapulakam', 'LLLLLLLLLLLLLLLLLLLLLLLG')
AddSamavrtta('mattākrīḍam', 'GGGGGGGGLLLLLLLLLLLLLLG')
AddSamavrtta('sāravarohā', 'GLLGGLLLLGGLLLLG')
AddSamavrtta('kaucamāraḥ', 'LLGGGLGG')
AddArdhasamavrtta('samudrakāntā', 'GGLLGLGLGG', 'GGGLLGLGLGG')
AddSamavrtta('bhīmābhogaḥ', 'GGGGGLGGLGGGGGGGLGGLGG')
AddSamavrtta('tanumadhyā', 'GGLLGG')
AddSamavrtta('kalasvanavaṁśaḥ', 'GLLGLLGGLLG')
AddVishamavrtta('varāsikā', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG')
AddSamavrtta('vidhunidhuvanam', 'GGGLLLLLLGGLLLLGGGG')
AddSamavrtta('kūlam', 'GGLLLGGGGG')
AddSamavrtta('madanamālā', 'LLLGLGLLLGG')
AddSamavrtta('bhūridhāmā', 'LLGGLGG')
AddSamavrtta('sāmikā', 'GLGGLGG')
AddSamavrtta('śrutakīrttiḥ', 'LLLLGGGLLGG')
AddSamavrtta('sūriṇī', 'GLGGG')
AddSamavrtta('kāmalā', 'LLLLLLGGGLGGLG')
AddSamavrtta('mitasakthi', 'LLLLLGLLGLGLLGG')
AddArdhasamavrtta('pātaśīlā', 'LLGLLLGGGLGG', 'GGLGGGGLGG')
AddArdhasamavrtta('vargavatī', 'GLLGLLGLLGG', 'LLGLLGLLGG')
AddSamavrtta('lakṣaṇalīlā', 'GLLGGLGGGGG')
AddSamavrtta('karañji', 'LGLLLLGG')
AddSamavrtta('viśvaviśvāsaḥ', 'GGGLGGLGGLGGGLGGGGGGLGGLGG')
AddSamavrtta('bhujaṅgaḥ', 'LGGLGGLGGLGGLGGLGGLGGLGG')
AddSamavrtta('nandaḥ', 'GLGG')
AddSamavrtta('lalanā', 'GLLGGGLLGLLG')
AddSamavrtta('bahulayā', 'GLGLLLG')
AddSamavrtta('dhamanikā', 'LLGLGLLLLG')
AddSamavrtta('bhārāvatāraḥ', 'LLLGGLLGLLLLLLLGGLGG')
AddSamavrtta('vārayātrikam', 'GLLGLGGLGLG')
AddSamavrtta('paragatiḥ', 'GLGLLLLLGLLLG')
AddSamavrtta('vidhāritā', 'LGLLGLLGLGLG')
AddSamavrtta('sudhādharā', 'GLGLGLGGLGLGLG')
AddSamavrtta('dārikā', 'LLGLGLLLGLG')
AddSamavrtta('asitadhārā', 'LLGLLLLLGG')
AddSamavrtta('bhāṣā', 'LGGGLGLG')
AddSamavrtta('saṅkalpāsāraḥ', 'GGGGGGGGGGGGGG')
AddSamavrtta('vindhyārūḍham', 'GGGGLGGGGGGLGG')
AddSamavrtta('holā', 'LLLGGGG')
AddArdhasamavrtta('śiśiraśikhā', 'LLLLLLGLGLG', 'LLLLGLLGLGLG')
AddSamavrtta('śākhoṭaki', 'LLLGGGLG')
AddSamavrtta('bhasalavinoditā', 'LGLGLLLLLGLG')
AddSamavrtta('niskā', 'GGGLLG')
AddSamavrtta('abhīrukā', 'LGLGLLLLLLLLG')
AddSamavrtta('apayodhā', 'LLGGLGGGGGG')
AddSamavrtta('sarāvikā', 'LGLGLGLGLG')
AddSamavrtta('saraghā', 'LLGGGLLG')
AddSamavrtta('kuhū', 'LGLLGLLGG')
AddSamavrtta('viṣamavyālī', 'LLLLLGGGGGGG')
AddVishamavrtta('indumā', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG')
AddSamavrtta('candrahāsakarā', 'GLGLLGLGLLGLG')
AddSamavrtta('indhā', 'GGLGLG')
AddArdhasamavrtta('lāsyalīlālayaḥ', 'GGLLGGGLGGLGG', 'GLLLLGGGLGGLGG')
AddSamavrtta('adhīrā', 'GLLGGGG')
AddSamavrtta('jaloddhatagatiḥ', 'LGLLLGLGLLLG')
AddSamavrtta('dhīradhvānam', 'GGGGGGGGGLLGGG')
AddArdhasamavrtta('arbhakapaṅktiḥ', 'LLGGLLGLGLGG', 'GLLGLLGLGLGG')
AddArdhasamavrtta('anūpakam', 'LLLLGLLGLGLG', 'LLGLLGLGLG')
AddSamavrtta('kusumavicitrā', 'LLLLGGLLLLGG')
AddSamavrtta('kiśalayam', 'LLLGGGG')
AddSamavrtta('kumudinīvikāśaḥ', 'LGLGGLLLGLGG')
AddSamavrtta('svidā', 'LGLLLLG')
AddSamavrtta('vāsakalīlā', 'GLLGGGLLGGGLLGGGLLGGGG')
AddSamavrtta('uditam', 'LLGLLGLLGG')
AddSamavrtta('sthālī', 'GGLGLG')
AddSamavrtta('vāsaramaṇikā', 'GLLLLGLLGGLG')
AddSamavrtta('bhūrivasu', 'LGGGLLG')
AddSamavrtta('madanalalitā', 'GGGGLLLLLGGGLLLG')
AddSamavrtta('asambādhā', 'GGGGGLLLLLLGGG')
AddSamavrtta('madalekhā', 'GGGLLGG')
AddSamavrtta('vaṁśalonnatā', 'GLGLGLGLGGGGGGGLGLGLGGGG')
AddSamavrtta('yugadhāri', 'LLGLGGGG')
AddSamavrtta('śalkaśakalam', 'GLLLGLLGLLG')
AddSamavrtta('hāsikā', 'GGGLG')
AddSamavrtta('mantharāyanam', 'LLLGLGLLLLLLGLLGLLGLLGG')
AddSamavrtta('nārācikā', 'GGLGLGLG')
AddSamavrtta('cakoraḥ', 'GLLGLLGLLGLLGLLGLLGLLGG')
AddSamavrtta('masṛṇam', 'LLLLLLGGG')
AddSamavrtta('sindhuk', 'GGLLLLLG')
AddSamavrtta('elā', 'LLGLGLLLLLLLLGG')
AddSamavrtta('prapātalikā', 'GLLLLGLGLGLLG')
AddSamavrtta('rasadhārā', 'LLLLGGLLLLGGG')
AddArdhasamavrtta('ulapohā', 'GLLGLLGLGLGG', 'LLGGLLGLGLGG')
AddSamavrtta('nirvindhyā', 'LGLLLGGGG')
AddSamavrtta('upohā', 'LGGLGLG')
AddSamavrtta('ari', 'GLLLLLLG')
AddSamavrtta('pākali', 'LLLGLGLG')
AddSamavrtta('marmasphuram', 'GGLGLLLGLGGLG')
AddArdhasamavrtta('sarasīkam', 'GGLGLLLGLLGG', 'LLGGLLLGLLGG')
AddSamavrtta('ādhidaivī', 'LGGGGGLGGLGG')
AddSamavrtta('vīranīrājanā', 'LGGLGGLGGLGGGLGGLGGLGG')
AddSamavrtta('adhīrakarīram', 'GGGLLLLLLGLLLLGLLLLGLLGG')
AddSamavrtta('haṁsamālā', 'GLGGLGG')
AddSamavrtta('sṛtamadhu', 'LLGGLLLG')
AddSamavrtta('savyālī', 'GGGGGGGGGGGGG')
AddSamavrtta('mārābhisaraṇam', 'GGLLLLGGGGLLLLGLGGG')
AddSamavrtta('nirmuktamālā', 'GGGGLGGLLLLLLG')
AddSamavrtta('akṣarāvalī', 'GLGLLGLGLG')
AddSamavrtta('pañcaśākhī', 'LLLLLGLGLGG')
AddSamavrtta('kumudamālā', 'LLLGGLLLGGLLLGGLLLGGLLLGG')
AddSamavrtta('rasabhūma', 'LLGLGLLLGG')
AddArdhasamavrtta('upodgatā', 'LLGGLLGLGLGG', 'LLGLLGLGLGG')
AddSamavrtta('avoḍhā', 'GGGGLG')
AddVishamavrtta('mālā', 'LGLGGLLGLGG', 'LGLGGLLGLGG', 'GGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('somarājī', 'LGGLGG')
AddSamavrtta('gūrṇikā', 'GLGGGLG')
AddSamavrtta('paṅkavatī', 'GLLLLLLGLLGLG')
AddSamavrtta('manmathaḥ', 'LLGLLGGLLGLLGG')
AddSamavrtta('saudāmanadāma', 'LLGLLGLLGLLGLLLLGLLGGLLGG')
AddSamavrtta('madhumārakam', 'LLGLGG')
AddSamavrtta('caṇḍī', 'LLLLLLLLGLLGG')
AddSamavrtta('kharviṇī', 'GLGGGGG')
AddSamavrtta('bhujaṅgoddhatam', 'GGLGLLGLGGLGLLGGLGLLLG')
AddSamavrtta('ārādhinī', 'GGLGGGGGGGG')
AddSamavrtta('kanakamālikā', 'GLGLLLGLGLLLGLGLLLGLG')
AddSamavrtta('ruciram', 'GLLLLGG')
AddSamavrtta('arti', 'LGGLLG')
AddSamavrtta('nameruḥ', 'GGLLGLGLGG')
AddSamavrtta('nīlaśārdūlam', 'LLLLLLGGGLGGLGGLGG')
AddSamavrtta('kalāpāntaritā', 'LGGLLGLGGG')
AddArdhasamavrtta('aupagavam', 'LLLGLGGLGLG', 'GLLGLGGLGLG')
AddSamavrtta('virataprabhā', 'GLLGLLLLLGLG')
AddSamavrtta('vīravaṭu', 'LLLGLLG')
AddSamavrtta('kūlacāriṇī', 'GLGLGLGGGGG')
AddSamavrtta('mattagajendraḥ', 'GLLGLLGLLGLLGLLGLLGLLGG')
AddSamavrtta('vidyunmālā', 'GGGGGGGG')
AddSamavrtta('pravahlikā', 'GLLLGLGLG')
AddSamavrtta('śraddharā', 'GLGLGLLG')
AddSamavrtta('sphoṭakṛīḍam', 'LLLLGGGGGGGGGGG')
AddSamavrtta('mañjumālatī', 'GLGLGLLLGLGLG')
AddSamavrtta('komalakalpakalikā', 'LLGLGGLLGLLLG')
AddSamavrtta('lalāmalalitādharā', 'LGLGLGLGLGLG')
AddSamavrtta('amandapādaḥ', 'GLLLLGLGLGG')
AddSamavrtta('udayanamukhī', 'LLLLLGLLLLLG')
AddArdhasamavrtta('viśvapramā', 'GGLGGLGGLG', 'LGLGGLGGLG')
AddSamavrtta('madanakam', 'LLLLLLLLG')
AddSamavrtta('upagataśikhā', 'LLLLLGLGLLGLG')
AddSamavrtta('kuṭhārikā', 'LGLGGLG')
AddArdhasamavrtta('avarodhavanitā', 'LLLGLLGLLGLGLG', 'LLGLLGLGLGLLLGG')
AddSamavrtta('viśvamukhī', 'GLLGLLGLLG')
AddSamavrtta('upasthitā', 'GGLLGLLGLGG')
AddSamavrtta('śunakam', 'GLLGLG')
AddSamavrtta('parabhānu', 'LGGLLGG')
AddSamavrtta('vihāvā', 'LGGLGGLG')
AddSamavrtta('virāmavāṭikā', 'LLLLGLGLGLLGLLLLGLGLGLLLLG')
AddSamavrtta('upasaṁkulā', 'LLGLGLGGLG')
AddSamavrtta('kanakitā', 'GLLGLLLLLLLLG')
AddArdhasamavrtta('upasarasīkam', 'LLGGLLLGLLGG', 'GGLGLLLGLLGG')
AddSamavrtta('jāsari', 'GLLLGLG')
AddSamavrtta('nūtanam', 'GLGLLLGLLGLLGLG')
AddArdhasamavrtta('bhadrā', 'GGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('strī', 'GG')
AddSamavrtta('pathyā', 'LLGLGLLLGLGGLG')
AddSamavrtta('sūrasūcakaḥ', 'GGGLLGLGLLLGLLGLLGLGGLGGLG')
AddSamavrtta('apavāhaḥ', 'GGGLLLLLLLLLLLLLLLLLLLLGGG')
AddVishamavrtta('saurabheyī', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG')
AddSamavrtta('sāvaṭu', 'LGLGLG')
AddSamavrtta('kāntāram', 'LGGGGGLLLLLGGLGGG')
AddSamavrtta('prapañcacāmaram', 'LLLLLLGLGLGLGLGLGLG')
AddSamavrtta('tomaram', 'LLGLGLLGG')
AddSamavrtta('kalādhāmam', 'GLLGLLLGLGGGG')
AddSamavrtta('kṛtamālam', 'GGLLGLLGGGLLGG')
AddSamavrtta('dharā', 'GGLG')
AddSamavrtta('upalinī', 'LLLGLGLG')
AddSamavrtta('caturīhā', 'LGLGLLGG')
AddSamavrtta('saramāsaraṇiḥ', 'LLGLLGGGLGGLGG')
AddSamavrtta('chāyā', 'LGGGGGLLLLLGGGLGGLG')
AddSamavrtta('rasikarasālā', 'LLLLLLLLGLLGGLLGGLLLLLLGG')
AddSamavrtta('jvalitā', 'LLGLLLLLLLLG')
AddSamavrtta('kroḍāntikam', 'GGLGLLG')
AddSamavrtta('virohi', 'LGLLLGG')
AddSamavrtta('parimitavijayā', 'LLLLLLGLGLGG')
AddSamavrtta('vṛntam', 'LLGGGGLG')
AddSamavrtta('hīrāṅgī', 'GGGLLLLGGG')
AddSamavrtta('vipannakadanam', 'LLLGLGLLLGGGG')
AddSamavrtta('sāndrapadam', 'GLLGGLLLLGG')
AddSamavrtta('vanavāsinī', 'LLGLLGLGLGLLGLGLLLLLGG')
AddSamavrtta('pikālī', 'GLGLGG')
AddSamavrtta('vāmavadanā', 'GLLLGLGGLGGLG')
AddSamavrtta('vikasitapadmāvalī', 'LLLLGGLGGGG')
AddSamavrtta('vinatākṣī', 'LLGGLLLLLLLLG')
AddArdhasamavrtta('yuddhavirāṭ', 'GGGLLGLGLGG', 'GGLLGLGLGG')
AddSamavrtta('dṛtiḥ', 'LLLLLGG')
AddArdhasamavrtta('kiṁśukāvalī', 'GGGLLLLGLGLGG', 'GGLLGLGLGG')
AddSamavrtta('sairavī', 'GLGGGGG')
AddSamavrtta('saṁlakṣyalīlā', 'LLLGLGLLLGLGLLLGGLGG')
AddSamavrtta('kūrcalalitam', 'GLGGLGGLGGLLLG')
AddSamavrtta('anṛju', 'GLLG')
AddSamavrtta('madirā', 'GLLGLLGLLGLLGLLGLLGLLG')
AddSamavrtta('śikhilikhitā', 'GGGLLLLG')
AddSamavrtta('saralāṅghri', 'GGLLLGG')
AddSamavrtta('līlālekhaḥ', 'GGGGGGGGGGGGGGG')
AddSamavrtta('śakuntakuntalaḥ', 'GGGGLGGLGLLLLLLGLGLGLGLGLG')
AddSamavrtta('krīḍā', 'LGGG')
AddSamavrtta('vātuli', 'LGGLGGLG')
AddSamavrtta('kumāralīlā', 'GGGLLLLLLGLGLGG')
AddSamavrtta('vāsavilāsavatī', 'GLLGLLGLLGGGG')
AddSamavrtta('rūpāvaliḥ', 'GGLLLLLLLLLG')
AddSamavrtta('kṣamāpāli', 'LGLGGG')
AddSamavrtta('prajñāmūlam', 'GGGGLLLLLLGGG')
AddArdhasamavrtta('surahitā', 'LLLLLLLLGLLGG', 'GGLLLLLLLLLLG')
AddSamavrtta('gahanā', 'GLLLLLGLLG')
AddSamavrtta('bhekālokaḥ', 'GLLGGGGGGGGLLLLLLGGG')
AddSamavrtta('vellitavelam', 'GLLGLLGLLGGGLLGLLLLLLLLG')
AddSamavrtta('ambudāvalī', 'LLGLGGLLGLGLG')
AddArdhasamavrtta('luptā', 'LLGGLLGLLGLG', 'LLGLLGLLGLG')
AddSamavrtta('vilambanīyā', 'LLLGLLLLGLGLGG')
AddSamavrtta('kuśalakalāvatikā', 'GGGLLLLGLLG')
AddSamavrtta('siṁhalekhā', 'GLGLGLGG')
AddSamavrtta('kelicaram', 'LLLLGGLLLLG')
AddSamavrtta('mṛgendramukham', 'LLLLGLLGLGLGG')
AddSamavrtta('vīraviśrāmaḥ', 'LLLLLLGLGLLLGLGGG')
AddSamavrtta('haṁsarutam', 'GGGLLLGG')
AddSamavrtta('madāvadātā', 'LLGGLLGLGLGLGG')
AddSamavrtta('sampākaḥ', 'GGGGGLG')
AddSamavrtta('vīravikrāntaḥ', 'GGGLLLLGLGGLGGLGGLGGLGGLGG')
AddSamavrtta('lakṣmī', 'GLGGLGGG')
AddSamavrtta('nandanam', 'LLLLGLGLLLGLGLGGLG')
AddSamavrtta('kuhakakuharam', 'LLLLLLGGGLGGLLLLLLGGGLGGLG')
AddSamavrtta('vāravatī', 'LLGGLLGLLG')
AddSamavrtta('ārbhavam', 'GLGLGG')
AddSamavrtta('līlālolaḥ', 'GGGGLLLLGGGGG')
AddSamavrtta('vaśamūlam', 'LLGGLLLLGLGLGG')
AddSamavrtta('vayasyaḥ', 'LGGGLGG')
AddSamavrtta('kharpari', 'LGLGGLG')
AddSamavrtta('sambodhā', 'LGLGGLLLLLLGGG')
AddSamavrtta('tāmarasam', 'LLLLGLLGLLGG')
AddSamavrtta('rucirā', 'LGLGLLLLGLGLG')
AddSamavrtta('pañjari', 'GLLGGGLG')
AddSamavrtta('vilulitamañjarī', 'LLLLGLGGGGG')
AddSamavrtta('arthaśikhā', 'GLLLLLLGLLG')
AddSamavrtta('lodhraśikhā', 'GGGLLGLLGLLGG')
AddSamavrtta('kiñjalki', 'GGLGG')
AddSamavrtta('pataṅgapādaḥ', 'LGLGGLGGLGGLGGLGGG')
AddArdhasamavrtta('jāriṇī', 'LLLGGLGGLG', 'GLGGLGLLLGGLG')
AddSamavrtta('viśambhari', 'LLLLLLLGGLLLLG')
AddSamavrtta('akhaniḥ', 'LLLLGLLG')
AddSamavrtta('jālapādaḥ', 'GGLGGGGLGGG')
AddSamavrtta('kāṇḍamukhī', 'LGLGLLGLLG')
AddSamavrtta('indraphalā', 'GLLGGGGG')
AddArdhasamavrtta('kalanāvatī', 'LLGLGLLLGLGLG', 'LLGLGLLLGLLGG')
AddSamavrtta('kañjā', 'LGLGGG')
AddSamavrtta('vṛddhavāmā', 'GGLGGLLGLGGLG')
AddSamavrtta('bhārṅgī', 'LGLLLGGG')
AddSamavrtta('kuradi', 'LGLLLLG')
AddSamavrtta('īḍā', 'GGLLLLLG')
AddSamavrtta('śroṇī', 'LGLGGGG')
AddSamavrtta('paṭupaṭṭikā', 'LLGLGLLGLGG')
AddSamavrtta('maśagā', 'LGGLLG')
AddSamavrtta('vedhāḥ', 'GGLLGGG')
AddSamavrtta('meghālokaḥ', 'LGGGGGGGG')
AddSamavrtta('anucāyitā', 'LLLLLGLGLG')
AddSamavrtta('pratisīrā', 'GGGGLLGG')
AddSamavrtta('sutalam', 'LLGGLGLLGGLG')
AddSamavrtta('harṣiṇī', 'GLGGLLG')
AddArdhasamavrtta('vaisārī', 'GGLLGLGLG', 'GGGLLGLGLG')
AddArdhasamavrtta('apramāthinī', 'LLGGLLGLGLGG', 'LLLLGLLGLGLGG')
AddSamavrtta('puṭamardi', 'LLLLGG')
AddSamavrtta('samayaprahitā', 'LLGLLGLGGLGG')
AddSamavrtta('viśālāntikam', 'GGLGGLGGLG')
AddSamavrtta('śṛkhalavalayitam', 'GLLLLLLLLGLLGGGLLLLLLLGLLG')
AddSamavrtta('parimalalalitam', 'LLLLLLGGLGG')
AddSamavrtta('mandari', 'GLG')
AddSamavrtta('kamalaśikhā', 'LLLLGGGGGGLLLLGLLGLLG')
AddSamavrtta('sthūlā', 'GGLLLGG')
AddSamavrtta('ahilā', 'GGLLLGLGLG')
AddSamavrtta('prabhā', 'LLLLLLGLGGLG')
AddSamavrtta('upasthitam', 'LGLLLGGGLGG')
AddSamavrtta('śarabhūriṇī', 'GLGLLGLGLLGLGLLGLGLLGLGGG')
AddSamavrtta('vaisāruḥ', 'GGLLLGGGG')
AddSamavrtta('pratari', 'GLGLLG')
AddSamavrtta('vārttāhārī', 'LLLLGLLGGGG')
AddSamavrtta('nābhasam', 'LGLLGLLLGLG')
AddSamavrtta('vīrāntā', 'LGLLLGGGGG')
AddSamavrtta('kumbhakam', 'LLLLLLGLGGLGGLGGLGGLGGLGGG')
AddSamavrtta('nimagnakīlā', 'LGLGGLLGLGGG')
AddSamavrtta('vāri', 'LGGG')
AddSamavrtta('saubhagakalā', 'GLLLGLLLGLG')
AddArdhasamavrtta('haṁsī', 'LGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('śeṣāpīḍam', 'GGGGLLLLGLG')
AddSamavrtta('viplutaśikhā', 'GLLLGLGLGGLG')
AddArdhasamavrtta('sudhā', 'GGGLLGLGLG', 'LLGGLLGLGLG')
AddSamavrtta('ābhāsamānam', 'LGGLGGLGGLGGGGLGGLGGLGGLGG')
AddSamavrtta('mallapallīprakāśam', 'LGGLGGLGGLGGLGGLGGLGGLGGG')
AddArdhasamavrtta('hīnatālī', 'LLGGLLLLGLGLGLGG', 'GGGLLLLGLGLG')
AddArdhasamavrtta('karadhā', 'GGGLLGLGLG', 'LLLLLLGLGLG')
AddSamavrtta('vipākavatī', 'LLLGLLLGLLGLLG')
AddSamavrtta('varkaritā', 'GGGGLLG')
AddSamavrtta('gītikā', 'LLGLGLLGLGLLGLGLLGLG')
AddSamavrtta('visasi', 'LLGLLG')
AddArdhasamavrtta('baddhā', 'GGGGLLLLLLG', 'LLGLLGLLLLLLG')
AddSamavrtta('āśāpādaḥ', 'GGGGLLLLGLG')
AddSamavrtta('suvadanā', 'GGGGLGGLLLLLLGGGLLLG')
AddSamavrtta('kuśakam', 'GLGLLLLG')
AddSamavrtta('ujjvalā', 'LLLLLLGLLGLG')
AddArdhasamavrtta('kāmākṣī', 'LLGLLGLLLLLLG', 'GGGGLLLLLLG')
AddSamavrtta('acalanayanam', 'LLLLLLLLLLLLLLLLG')
AddSamavrtta('pravādapadā', 'LLGLGLGLLG')
AddSamavrtta('bhramaravilasitā', 'GGGGLLLLLLG')
AddArdhasamavrtta('ākhyānakī', 'GGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('manthānakam', 'GGLGGG')
AddSamavrtta('bhujalatā', 'LLLLLGGGLLG')
AddSamavrtta('mayūkhasaraṇiḥ', 'GLLLLGLGLLLGG')
AddSamavrtta('unnarma', 'GLLGLLLLGLLGGG')
AddSamavrtta('kālavarma', 'LLLGLLLGLGG')
AddSamavrtta('phaladharam', 'LLLLLLGLLG')
AddSamavrtta('suri', 'LLLLGGG')
AddSamavrtta('bhāsitabharaṇam', 'GLLLLGGGGGGG')
AddSamavrtta('bhasalaśalākā', 'GGGGLLLLGGGGLLLLGGGGLLLLGG')
AddSamavrtta('krūrāśanam', 'GGLLLLGGLLLLLLGGG')
AddArdhasamavrtta('pāṭalikā', 'LLLLGGLLLLGG', 'GLLGLLGLLGG')
AddSamavrtta('vaśaṁvadaḥ', 'LLGLLGLLGLLGLLGLLGLLGLLGLG')
AddArdhasamavrtta('bhadravirāṭ', 'GGLLGLGLGG', 'GGGLLGLGLGG')
AddSamavrtta('nimnāśayā', 'GGLGGGG')
AddSamavrtta('vilambitamadhyā', 'GGGLLGLLGGG')
AddSamavrtta('acaṭu', 'LLLLLLG')
AddSamavrtta('kṛtakavali', 'LLLLLLLLLG')
AddSamavrtta('dorlīlā', 'LLGLLGLGGGGG')
AddSamavrtta('kāmaśālā', 'GLGGLGGLGGLGGG')
AddSamavrtta('valgā', 'GGLGGLGGG')
AddSamavrtta('kaṁsari', 'GGGGLG')
AddArdhasamavrtta('madākrāntā', 'LLGLLGLGLGLGG', 'GGGLLGLGLGLGGG')
AddSamavrtta('sarasī', 'LLLLGLGLLLGLLGLLGLGLG')
AddSamavrtta('pūrṇā', 'GGLLGLG')
AddSamavrtta('bhāratī', 'GGGGGGGGGGG')
AddSamavrtta('mṛgendu', 'LGG')
AddSamavrtta('sarojāvālī', 'LGGLGGGLGGLG')
AddSamavrtta('sukhaśailam', 'GGGGLLGGLLGG')
AddSamavrtta('kumāralalitā', 'LGLLLGG')
AddSamavrtta('kamanī', 'LLGLGG')
AddSamavrtta('anantadāmā', 'LLLLLLLLGLGLGG')
AddArdhasamavrtta('kilikitā', 'GLGLLLGLGLG', 'LLLGLLLGLGLG')
AddSamavrtta('varajāpi', 'GLLLLGG')
AddSamavrtta('tanvī', 'GLLGGLLLLLLGGLLGLLLLLLGG')
AddSamavrtta('gajagatiḥ', 'LLLGLLLG')
AddSamavrtta('vireki', 'GLGLLLGLGG')
AddSamavrtta('sāhūti', 'GGGGGG')
AddSamavrtta('pariṇāhī', 'GGGGLLLLGGLLGG')
AddSamavrtta('vidhuravitānam', 'LLLLLLGLLLLGG')
AddSamavrtta('gaṅgodakam', 'GLGGLGGLGGLGGLGGLGGLGGLG')
AddArdhasamavrtta('korakitā', 'GLLGLLGLLGG', 'LLLLGGLLLLGG')
AddSamavrtta('indraḥ', 'LGLLGLLGGG')
AddSamavrtta('upadhānam', 'LGLLLLLGLLGG')
AddSamavrtta('pāñcālāṅghriḥ', 'LLLLGGGG')
AddSamavrtta('bhujaṅgajuṣī', 'GLGLLGGLGLLG')
AddSamavrtta('citibhṛtam', 'LLLLLLLGLG')
AddSamavrtta('maṇimālā', 'GGLLGGGGLLGG')
AddSamavrtta('viyogavatī', 'LGLLGLLLLLLG')
AddSamavrtta('indravadanā', 'GLLLGLLLGLLLGG')
AddSamavrtta('lulitam', 'LLGLLGLLGG')
AddSamavrtta('māṇavakam', 'GLLGGLLG')
AddArdhasamavrtta('upāḍhyam', 'GLLGLLGLGLGG', 'LLLLLGLGLGG')
AddSamavrtta('niśipālam', 'GLLLGLLLGLLLGLG')
AddSamavrtta('viṣvagvitānam', 'GGLGLLLGLLLLGGLGGLGG')
AddVishamavrtta('saurabhakam', 'LLGLGLLLGG', 'LLLLLGLGLG', 'GLGLLLGLLG', 'LLGLGLLLGLGLG')
AddSamavrtta('śraddharāntā', 'GLGGLGGLGGLGG')
AddSamavrtta('hemahāsaḥ', 'GLGGLGGLGG')
AddArdhasamavrtta('aupagavītam', 'GLLGLGGLGLG', 'LLLGLGGLGLG')
AddSamavrtta('amanā', 'LLGLLGLG')
AddSamavrtta('pulakāñcitam', 'GLLLLGLLLLGGLLLLLLGLLGG')
AddSamavrtta('vīvadhaḥ', 'LLLLGLLLGLG')
AddSamavrtta('ulkābhāsaḥ', 'GGGGGLLLGGGGG')
AddSamavrtta('kirātaḥ', 'LLLLGLGGLGGLG')
AddSamavrtta('amānikā', 'LGLGLGGG')
AddSamavrtta('dadhi', 'GLLGLLGLG')
AddSamavrtta('gaṇadehā', 'LLGGGGLLGG')
AddSamavrtta('vainasam', 'GLGLG')
AddSamavrtta('alālāpi', 'LLGLGGG')
AddSamavrtta('prasarā', 'GGGLLGLLGG')
AddSamavrtta('bhūriśobhā', 'GGGGGGLLLLLLGGLGGLGG')
AddSamavrtta('vabhrūḥ', 'GGLGGG')
AddSamavrtta('kumbhāri', 'GGGGG')
AddSamavrtta('arjitaphalikā', 'GLLLLGGLGLLG')
AddSamavrtta('samāhitam', 'LLLLGLLGLLGLLGLLGLLGLLGG')
AddSamavrtta('parabhṛtam', 'LLLGGLG')
AddSamavrtta('pārthivam', 'LGLLLGLGLLLGLLLGLG')
AddSamavrtta('visraṁsi', 'LLLLLGGGLG')
AddVishamavrtta('śālā', 'GGLGGLLGLGG', 'GGLGGLLGLGG', 'LGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('hemarūpam', 'GLGGLGLG')
AddSamavrtta('jaladarasitā', 'LLLLLGLGGLGGLG')
AddSamavrtta('mālatikā', 'LGLLGG')
AddSamavrtta('antarvikāsavāsakaḥ', 'GGLGLGLGLGLG')
AddSamavrtta('phalinī', 'LLLLGGGLLG')
AddSamavrtta('vasupadamañjarī', 'LLLLGLGLLLGLLGLGLG')
AddSamavrtta('candralekhā', 'GGGGLLLLLLGGLGGLGG')
AddSamavrtta('vāṭikāvikāśaḥ', 'GLLLLLLGGLGLGG')
AddSamavrtta('madanayā', 'LLLLLLGGLLG')
AddArdhasamavrtta('karabhoddhatā', 'GLLGGLGLGLG', 'LLGLLLGLGLG')
AddSamavrtta('vikalavakulavallī', 'LLLLLLGGLGGG')
AddSamavrtta('mālādharaḥ', 'LLLLLGLGLLLGLGGLG')
AddSamavrtta('kāṁsīkam', 'GGGLLLLGG')
AddSamavrtta('upacitram', 'LLGLLGLLGLG')
AddSamavrtta('subhadrikā', 'LLLLLLGLGLG')
AddSamavrtta('vitānitā', 'LLLLLLLLLGLGLG')
AddSamavrtta('kāmanibhā', 'GGGLLGGGLG')
AddSamavrtta('kuḍaṅgikā', 'LGLGLGLGLGLGLG')
AddSamavrtta('paṇavaḥ', 'GGGLLLLGLG')
AddSamavrtta('anukūlā', 'GLLGGLLLLGG')
AddSamavrtta('vijohā', 'GLGGLG')
AddSamavrtta('krīḍāyatanam', 'LLGLLGLLGGGLLG')
AddSamavrtta('prapannapānīyam', 'GGLLGGGGLGLGGG')
AddArdhasamavrtta('ālepanam', 'LLLGGLGGLGGLG', 'LLLGLLLGGLGGLG')
AddSamavrtta('dhṛtahālā', 'GGGGLLGGG')
AddSamavrtta('parivṛḍham', 'LLLGGLGGLGGLG')
AddArdhasamavrtta('dhīrāvarttaḥ', 'GGGGGLLGGLLGG', 'GGGGLLLLGGGGG')
AddSamavrtta('grāvāstaraṇam', 'GGGGLLLLGGLLGGGGLLG')
AddArdhasamavrtta('upameyā', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG')
AddSamavrtta('kṛṣṇagatikā', 'GLLLGLGG')
AddSamavrtta('rādhikā', 'LLGGLLGLLGLG')
AddSamavrtta('śiśubharaṇam', 'LLLLLLLLLLLLLLGG')
AddSamavrtta('cārugatiḥ', 'LLLLLLLLGGGGLLLLGLGLGLGLGG')
AddSamavrtta('kāmacāri', 'GGLGLLGLGG')
AddSamavrtta('kanakaketakī', 'GGLLLGLGLLGLG')
AddSamavrtta('sarasamukhī', 'GGLLLLLLGG')
AddSamavrtta('salekhā', 'LLLLLLGGGLLLLLLGG')
AddSamavrtta('bhadrakam', 'GLLGLGLLLLLGLLLGLGLLLG')
AddSamavrtta('devalam', 'GGGLGGG')
AddSamavrtta('vivaravilasitam', 'GGLLLLLLGGGG')
AddSamavrtta('līlācandram', 'GGGGGGGGLLGGLLG')
AddVishamavrtta('vāṇī', 'GGLGGLLGLGG', 'LGLGGLLGLGG', 'GGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('kaṭhināsthi', 'GLLLLLLGG')
AddSamavrtta('añcalavatī', 'GLLLGLLGLGLLLG')
AddSamavrtta('ahatiḥ', 'LGGLLLG')
AddSamavrtta('vātyā', 'GLLLGGGG')
AddSamavrtta('aśokapuṣpam', 'LLLLLLGLGLGLG')
AddSamavrtta('krośapadā', 'GLLGGGLLGGLLLLLLLLLLLLLLG')
AddSamavrtta('vaṁśāropī', 'LGGGLLGGGG')
AddSamavrtta('vidyādhāraḥ', 'GGGGGGGGGGGG')
AddSamavrtta('nāsābharaṇam', 'GGLLGGGLLGGLLG')
AddSamavrtta('halodgatā', 'LLLLGLGLG')
AddSamavrtta('uddhatikarī', 'GLLLGGGGGGG')
AddSamavrtta('hetiḥ', 'LLLLGLLGLGLLGG')
AddSamavrtta('karṇasphoṭam', 'LLLLGGGGLLLLGGGGG')
AddSamavrtta('bhaurikam', 'GLGGLGGLG')
AddSamavrtta('kokapadam', 'GLLGGGLLGGLLLLLLLLLLLLGG')
AddSamavrtta('sahajā', 'LLGLLGLGLG')
AddSamavrtta('lalitāgamanam', 'LLGLLGLGGGG')
AddSamavrtta('kalpadhāri', 'GLGGLGGLGLGLGLGG')
AddSamavrtta('kāmarūpam', 'GGGGLGGLLLLLGGLGG')
AddSamavrtta('celāñcalam', 'GGLGLLLLGLGLGG')
AddSamavrtta('gambhāri', 'GLGGLGGLGGG')
AddVishamavrtta('buddhiḥ', 'GGLGGLLGLGG', 'LGLGGLLGLGG', 'LGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('viśadacchāyaḥ', 'LLGGGLLGGG')
AddSamavrtta('kalki', 'GLGLG')
AddSamavrtta('kaṇikā', 'GGLLG')
AddSamavrtta('amati', 'GLLLLG')
AddSamavrtta('cañcarīkāvalī', 'LGGGGGGLGGLGG')
AddSamavrtta('hrīḥ', 'GLGGG')
AddSamavrtta('arditam', 'GLLGLLGLLGLLGLLGLLLLLLGG')
AddSamavrtta('kalpamukhī', 'GLLGGLG')
AddSamavrtta('drutalambinī', 'LLGLLGLGLLGLG')
AddSamavrtta('bimbam', 'LLLLLGLGG')
AddVishamavrtta('rāmā', 'GGLGGLLGLGG', 'GGLGGLLGLGG', 'LGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('lasadasu', 'LLLLLGLG')
AddSamavrtta('vyāhāri', 'GLLGGGG')
AddSamavrtta('kalāpatiprabhā', 'GLGLGLGLGLGLG')
AddArdhasamavrtta('camūrubhīruḥ', 'GLGLLLLGLGLG', 'LLGLLLLGLGLGG')
AddSamavrtta('suṣamā', 'GGLLGGGLLG')
AddSamavrtta('hrīṇahaiyaṅgavīnam', 'GLGGLGGLGGLGGLGGLGGLGGLGG')
AddSamavrtta('aḍamaruḥ', 'LLLLLLLLLLLLG')
AddSamavrtta('kulādhārī', 'LGGGLGGG')
AddSamavrtta('aparājitā', 'LLLLLLGLGLLGLG')
AddSamavrtta('keram', 'GLGGLLGLLG')
AddSamavrtta('mauktikadāma', 'LGLLGLLGLLGG')
AddSamavrtta('mahonmukhī', 'GGGLGLG')
AddSamavrtta('saṁhatikā', 'LLGLGLLGLG')
AddSamavrtta('asudhārā', 'LGLGLGGLGLGG')
AddSamavrtta('vinayavilāsaḥ', 'LLLLGGLLLLGGLLLLGGLLLLGGGG')
AddSamavrtta('subhadrāvataraṇiḥ', 'GGGGGLGGLLLG')
AddArdhasamavrtta('akoṣakṛṣṭā', 'LLGGLLGLGLGLGG', 'GGLLGLGLGG')
AddSamavrtta('ayamitam', 'LLLGLG')
AddSamavrtta('sārasanāvaliḥ', 'LLLGLLLGLLGLG')
AddSamavrtta('śantanu', 'GLLGGLG')
AddSamavrtta('kārpikā', 'GLGLGLG')
AddSamavrtta('amālīnam', 'LGGLGGGGGGG')
AddSamavrtta('sumohitā', 'LGLGGGG')
AddSamavrtta('cittacintāmaṇiḥ', 'GLGGLGGLGLLLLGLGGLGGLGGLG')
AddSamavrtta('vāntabhāraḥ', 'LLLGGLGG')
AddSamavrtta('paddhari', 'LGGGGLG')
AddSamavrtta('arilā', 'LLGGLLGLLGLG')
AddSamavrtta('mattebhavikrīḍitam', 'LLGGLLGLGLLLGGGLGGLG')
AddSamavrtta('mattālī', 'GGGGGLLGGGGG')
AddSamavrtta('amatiḥ', 'GGGLLLG')
AddSamavrtta('kāmukalekhā', 'GLLGGGLLGGG')
AddSamavrtta('mṛṣṭapādā', 'GLGGGLG')
AddSamavrtta('piculam', 'LLGLLGLGLGG')
AddSamavrtta('abhikhyā', 'LLGGGG')
AddSamavrtta('bhūrighaṭakam', 'GGGLLLGGGGG')
AddSamavrtta('śaṅkāvalī', 'GGLGLLGLGLLLLLG')
AddSamavrtta('kāsāram', 'GGGGGGGGLLLLGGLLG')
AddSamavrtta('vāṇīvāṇaḥ', 'GGGGLLLLGGLLGGLLGGGG')
AddSamavrtta('kumāragatiḥ', 'LGLLLLGLLLLG')
AddSamavrtta('paricāravatī', 'GGLGLLGLLG')
AddSamavrtta('vāhāntaritam', 'GGLLLLGLLGLLLLLLG')
AddSamavrtta('sūtaśikhā', 'GGLLGGLLGGLLLLGG')
AddSamavrtta('āpaṇikā', 'LGLGGLLGLLGLG')
AddSamavrtta('vallavīvilāsaḥ', 'GLGLGGLGGGG')
AddSamavrtta('kulyāvarttam', 'GGGGGGLLGGLLGGLG')
AddSamavrtta('manthari', 'GGGLGGLG')
AddSamavrtta('madanoddhurā', 'GLLGLLGLG')
AddSamavrtta('bhadrikā', 'GLGLLLGLG')
AddSamavrtta('jhillīlīlā', 'LLLLGGGGGGGGLGLGGGG')
AddArdhasamavrtta('paraprīṇitā', 'LLLLLLGGLGGLG', 'LLLLLLLLGGGLGGLG')
AddSamavrtta('paurasari', 'GLLGLLG')
AddSamavrtta('śārdūlalalitam', 'GGGLLGLGLLLGGGLLLG')
AddSamavrtta('kalpamīlitā', 'GLGGLGGLGGLGLG')
AddSamavrtta('amoghamālikā', 'LGLGLGLGGGG')
AddSamavrtta('nīpavanīyakam', 'GLLLLLLLLLLGGLLLLGLLGLLGG')
AddSamavrtta('saṅgamavatī', 'GLLLGLLLLLLG')
AddSamavrtta('abhidhātrī', 'LLGLLGLLGLGLGLGG')
AddArdhasamavrtta('alparutam', 'GLLLLLLGLLGLG', 'GLLLLLLGGLLLG')
AddVishamavrtta('premā', 'LGLGGLLGLGG', 'LGLGGLLGLGG', 'GGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('tanimā', 'LLLLLLLLGG')
AddSamavrtta('śobhā', 'LGGGGGLLLLLLGGLGGLGG')
AddSamavrtta('valīkendu', 'LLGGLGGG')
AddSamavrtta('aśaniḥ', 'LLLLLLGGLLLLG')
AddSamavrtta('mahanīyā', 'LGGLLGG')
AddSamavrtta('kalanāyikā', 'LGLGGLLLLLGLG')
AddSamavrtta('upodari', 'LGLLGLG')
AddSamavrtta('mālavikā', 'GGLLGLLLGLG')
AddSamavrtta('bodhāturā', 'LGGGGGLGGG')
AddSamavrtta('mudiram', 'LLGLLGLLGLLGLLGLLGLLGLLGG')
AddSamavrtta('paṭu', 'LLLG')
AddSamavrtta('vidyadālī', 'LGGLGGLGGLGGLGGLGGLGG')
AddSamavrtta('saurabhi', 'GLLLLG')
AddArdhasamavrtta('vegavatī', 'LLGLLGLLGG', 'GLLGLLGLLGG')
AddSamavrtta('rudrālī', 'LLLLLGGG')
AddSamavrtta('daṇḍī', 'GGLLLLGGLLLLGGLLLG')
AddSamavrtta('keśavatī', 'LGGGLLG')
AddArdhasamavrtta('āsavavāsitā', 'LLLGLLLGLGLGLGG', 'LLGGLLGLGLGLLLGG')
AddSamavrtta('krośitakuśalā', 'GLLLLGLLGGG')
AddSamavrtta('kīṭamālā', 'LLGLGLGGG')
AddSamavrtta('vindu', 'LGGGGG')
AddVishamavrtta('ramaṇā', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG')
AddArdhasamavrtta('anirayā', 'LLLGLLLLGLGLG', 'LLLGLLLGLLGLG')
AddSamavrtta('anāmayam', 'LGLLGLLGLLGLLGLLGLLGLLGG')
AddArdhasamavrtta('kāntā', 'GGGLLGLGLGG', 'GGLLGLGLGG')
AddSamavrtta('nirmedhā', 'LLLGGLGGGG')
AddSamavrtta('surasā', 'GGGGLGGLLLLLLGGLLLG')
AddSamavrtta('kāmā', 'GGLLLLLGG')
AddSamavrtta('kāladhvānam', 'GGGGGGLLLLGGGG')
AddSamavrtta('valvajam', 'GLLGLLGGLLLLLLGGG')
AddArdhasamavrtta('alipadam', 'GLGGLGLLLGGLG', 'LLLGGLGGLG')
AddSamavrtta('nālī', 'LGGGG')
AddSamavrtta('pāñcāli', 'GGG')
AddSamavrtta('varatrā', 'GLLLGLLGLLGG')
AddSamavrtta('valīmukhī', 'LGLGLG')
AddVishamavrtta('ṛddhiḥ', 'LGLGGLLGLGG', 'GGLGGLLGLGG', 'LGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('avanijā', 'LGLLGLGLG')
AddSamavrtta('ākhrṭam', 'GLGLGLLG')
AddSamavrtta('damanakam', 'LLLLLLLLLLG')
AddArdhasamavrtta('samayavatī', 'GGLLLLGGLLG', 'LLGGGGLLLLG')
AddSamavrtta('akhaṇḍamaṇḍanam', 'LGLGLGGLGLGLG')
AddSamavrtta('vyākośakośalam', 'GGLGLLLGGGLLLLGLLGLLGLGLG')
AddVishamavrtta('bālā', 'GGLGGLLGLGG', 'GGLGGLLGLGG', 'GGLGGLLGLGG', 'LGLGGLLGLGG')
AddSamavrtta('khaṭakā', 'LGLLGLLGLLG')
AddSamavrtta('harit', 'LLLLLGGG')
AddArdhasamavrtta('ghaṭikā', 'GGLLLGLGLG', 'LLGLLGLGLG')
AddSamavrtta('viralam', 'GLLLLGGLLG')
AddSamavrtta('śritakamalā', 'GLLGLLLLGGG')
AddSamavrtta('śravaṇābharaṇam', 'LLLLGLLGLLGLLGLLGLLGLLG')
AddSamavrtta('kalahakaram', 'LLLLLLLLLLLLGLLG')
AddArdhasamavrtta('vāsavavāsinī', 'LLLLGLGLLLGLLGLG', 'GGLLGLGLLLGLLGLG')
AddSamavrtta('ratirekha', 'GGLLGGGLLGLLGG')
AddSamavrtta('vimalā', 'LLGLLGLGLGG')
AddSamavrtta('staradhi', 'LGLGLLG')
AddSamavrtta('chalitakam', 'LLLGGLGLLG')
AddArdhasamavrtta('anālepanam', 'LLLGLLLGGLGGLG', 'LLLGGLGGLGGLG')
AddArdhasamavrtta('lāsyalīlā', 'GLLLLGGGLGGLGG', 'GGLLGGGLGGLGG')
AddSamavrtta('atikali', 'GGLLLG')
AddSamavrtta('taḍidambaram', 'GLLGLLGLLGLLGLLGLLGLG')
AddSamavrtta('ārabhaṭī', 'GLLGLLLLLLGLLGGG')
AddSamavrtta('maulimālikā', 'GLGLGGGG')
AddSamavrtta('dhāri', 'GLGG')
AddSamavrtta('viśālāmbhojālī', 'GGLLLGLGGGGG')
AddSamavrtta('karaśayā', 'LLLGLLGLG')
AddSamavrtta('citram', 'GLGLGLGLGLGLGLGG')
AddSamavrtta('udāttahāsaḥ', 'LGLGGLGLLLGLG')
AddSamavrtta('siktamaṇimālā', 'GLLLGGGGLLGG')
AddSamavrtta('vikacavatī', 'LLLLGGGLG')
AddSamavrtta('undari', 'GLLLGLG')
AddSamavrtta('vibhā', 'LLLLGGGGLLGGG')
AddSamavrtta('talpakatallajam', 'GLLGLLGLLGLLGLLLGLGGG')
AddSamavrtta('nandi', 'GLLGLG')
AddSamavrtta('dāmaghaṭitā', 'LLLLLLGLLLG')
AddSamavrtta('babhrulakṣmīḥ', 'GLGGLGGGLGGLGG')
AddVishamavrtta('udgatā', 'LLGLGLLLGG', 'LLLLLGLGLG', 'GLLLLLLGLLG', 'LLGLGLLLGLGLG')
AddSamavrtta('guñjā', 'GGLLGGG')
AddSamavrtta('kṣut', 'GLLLG')
AddSamavrtta('śivikā', 'GLLGLLGLLGLLGLLGLLGLLGLLG')
AddSamavrtta('lumbākṣī', 'LLGLLGLLLGGG')
AddSamavrtta('maṇihaṁsaḥ', 'LLGLGLLGLGLLGLG')
AddSamavrtta('rambhā', 'GGLLLLGGG')
AddSamavrtta('prahāṇaḥ', 'LGGGGGG')
AddSamavrtta('rasadhāri', 'LLGLGGG')
AddVishamavrtta('śīlāturā', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG')
AddSamavrtta('mattā', 'GGGGLLLLGG')
AddSamavrtta('kiraṇakīrttiḥ', 'GGLLGLGGLGLLLLLLLGG')
AddSamavrtta('rasikaparicitā', 'LLGGGLLLLLLG')
AddSamavrtta('niryatpārāvāraḥ', 'GGGGGLGGLGGLGG')
AddSamavrtta('saṁbhṛtaśaradhiḥ', 'GLLLLLLGGGLLLLLLGGLLGGG')
AddSamavrtta('hoḍapadā', 'GLLGLGG')
AddSamavrtta('bhīmārjanam', 'GGLGLGG')
AddSamavrtta('śāyinī', 'LLLLLGLGLGLLLGLGG')
AddSamavrtta('mauralikam', 'GLLGLLG')
AddSamavrtta('lāsyakārī', 'GLGGLGGLGGLGGLG')
AddSamavrtta('bhāvinīvilasitam', 'GLGLLLGLGLLLGLGLLLGLGLLLG')
AddSamavrtta('varddhiṣṇu', 'GGLGGGG')
AddSamavrtta('mayūrasāriṇī', 'GLGLGLGLGG')
AddSamavrtta('valā', 'GLLG')
AddSamavrtta('sarojavanikā', 'LGLLLGLGLGG')
AddSamavrtta('meghadhvanipūraḥ', 'GGLLGGGGGGG')
AddSamavrtta('viśeṣakabalitam', 'LLLLLLGGGGGGLGLLGLLGLLLLG')
AddSamavrtta('dhanadhari', 'LLGLLLG')
AddSamavrtta('siṁhapuccham', 'LGGLGGLGGLGGLGG')
AddSamavrtta('haravanitā', 'LLLLLLLLLLLLG')
AddSamavrtta('dārudehā', 'GLGGLGGLGGG')
AddArdhasamavrtta('īhā', 'LLLLGLLGLLGG', 'GLLGLLGLLGG')
AddSamavrtta('pramodaḥ', 'LLLLLLGLGGLGG')
AddArdhasamavrtta('vāsinī', 'GGLLGLGLLLGLLGLG', 'LLLLGLGLLLGLLGLG')
AddSamavrtta('moṭanakam', 'GGLLGLLGLLG')
AddSamavrtta('pramitākṣarā', 'LLGLGLLLGLLG')
AddSamavrtta('paritoṣā', 'LLGLLLLGLLGG')
AddSamavrtta('nirudam', 'LLGLLLLG')
AddArdhasamavrtta('atailam', 'LGLGGLGGLG', 'GGLGGLGGLG')
AddSamavrtta('arpitamadanā', 'GLLLLGLLLLGG')
AddSamavrtta('vanitāvilokaḥ', 'GGLGGLLLGLGG')
AddSamavrtta('sārddhapadā', 'GLGLGGLLGLGLG')
AddSamavrtta('dīpakam', 'GLLGGLLLLGGLLGG')
AddSamavrtta('guṇavatī', 'LLLGGG')
AddArdhasamavrtta('rucimukhī', 'LLLLLLLLGLLGG', 'LLLLLLGLLLLGG')
AddSamavrtta('sulūḥ', 'LLLLG')
AddSamavrtta('mañjīrā', 'GGGGGGGLLGGGLLGGGG')
AddSamavrtta('vidrumadolā', 'LLLLGGGGLLGG')
AddSamavrtta('mānavatī', 'LGLLGLLGLLGLLGLLGLLGLLG')
AddSamavrtta('paridhānīyam', 'LLLLLLGLLGGLLGLLGGLLGGG')
AddSamavrtta('muhurā', 'LLGLGLG')
AddSamavrtta('śarameyā', 'LLGGLLLGLLGG')
AddSamavrtta('mahī', 'LG')
AddArdhasamavrtta('pramālikā', 'LLGGLLGLGLGG', 'LLGLLGLGLGG')
AddSamavrtta('praguṇam', 'LLGGG')
AddVishamavrtta('vāsantikā', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG')
AddSamavrtta('śaśikalā', 'LLLLLLLLLLLLLLG')
AddSamavrtta('līlāratnam', 'GGGGGGLLGGGG')
AddSamavrtta('gahvaram', 'GLGGLGGLGLG')
AddSamavrtta('abhrabramaṇam', 'GGLLLLGGGLLGLLLLLLLLLLLLG')
AddSamavrtta('priyaṁvadaḥ', 'LLLGLLLGLGLG')
AddSamavrtta('snu', 'ल')
AddSamavrtta('vilulitavanamālā', 'LLLLLLGGGLLLLLLGGG')
AddSamavrtta('parviṇī', 'LLLLLLGLGLLLGLGGLG')
AddSamavrtta('atiraṁhaḥ', 'LGLLGLLGLGLGG')
AddVishamavrtta('upasthitapracupitam', 'GGGLLGLGLGLLGG', 'LLGLLLLGLGLGG', 'LLLLLLLLG', 'LLLLLLLLLLGLLGG')
AddSamavrtta('vīṇādaṇḍam', 'LGLLLGLGGGGG')
AddSamavrtta('lolalolambalīlam', 'GLGGLGGLGGLGGLGGLGG')
AddSamavrtta('svaravarṣiṇī', 'LLGLGLLGLGGG')
AddSamavrtta('svanakarī', 'LLLGLLG')
AddSamavrtta('ravonmukhī', 'GGLLGLGLG')
AddSamavrtta('śāntasurabhiḥ', 'GLLLLLGLGLLGLLG')
AddSamavrtta('suvṛttiḥ', 'LLGLLLLLLGG')
AddSamavrtta('naragā', 'LLLLGGLLGG')
AddSamavrtta('virājikarā', 'LGLLGGGG')
AddVishamavrtta('kīrtiḥ', 'LGLGGLLGLGG', 'GGLGGLLGLGG', 'GGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('cārvaṭakam', 'GGGGLLGLLGGGGGG')
AddSamavrtta('murajikā', 'LLLGGLG')
AddSamavrtta('saṁsṛtaśobhāsāraḥ', 'LLGGGLLGGGG')
AddSamavrtta('nāndīmukhī', 'LLLLLLGGLGGLGG')
AddSamavrtta('aśvagatiḥ', 'GLLGLLGLLGLLGLLLLG')
AddSamavrtta('vṛttahāri', 'LGGLGG')
AddSamavrtta('viratimahatī', 'GGLLLLLLLLGG')
AddSamavrtta('īhāmṛgī', 'GGLGLLGGLGG')
AddSamavrtta('nīrāñjaliḥ', 'GGLLLLGGLG')
AddSamavrtta('hīrakahāradharam', 'GLLGLLGLLGLLGLLGLG')
AddSamavrtta('nirasikā', 'LLLGLG')
AddSamavrtta('sphuṭaghaṭitā', 'LLLLGGLLG')
AddSamavrtta('mālīnam', 'GGGLG')
AddSamavrtta('kāru', 'LLGG')
AddSamavrtta('priyajīvitam', 'GLLGLLGLLGLLGLLGLLGLLGLLGG')
AddSamavrtta('pañcaśikhā', 'LLGLLGGG')
AddSamavrtta('uditavijohā', 'GGLGGLLLLGG')
AddArdhasamavrtta('sammadākrāntā', 'GGGLLGLGLGLGGG', 'LLGLLGLGLGLGG')
AddSamavrtta('dodhakam', 'GLLGLLGLLGG')
AddSamavrtta('dhṛṣṭapadam', 'GLLGLLLGLLGG')
AddSamavrtta('kurucarī', 'GLGGLLLG')
AddSamavrtta('śephālī', 'LGGGGGGGGG')
AddSamavrtta('anibhṛtam', 'LLLGGG')
AddSamavrtta('chalitakapadam', 'GGLLLLLGLLGG')
AddSamavrtta('vakrāvalokaḥ', 'LLLLLLGGGGLGGLGG')
AddSamavrtta('sambuddhiḥ', 'LLGGGLLGG')
AddSamavrtta('śampā', 'GGLLLLGGGGGG')
AddSamavrtta('anirbhāraḥ', 'LGGGGGGG')
AddSamavrtta('vahirvali', 'LGLLGLG')
AddSamavrtta('śambhuḥ', 'LLGGGLLGGGLLGGGGGGG')
AddSamavrtta('svinnaśarīram', 'GLLGGLGGLGGLG')
AddSamavrtta('bhūrimadhu', 'GGGGLLG')
AddSamavrtta('nirgalitamekhalā', 'LLLLLLGLGLLLGLLLGLG')
AddSamavrtta('hāriṇī', 'GGGGLLLLLLGGLGGLG')
AddSamavrtta('abhirāmā', 'LLGGLLGGLLLLG')
AddSamavrtta('śaragītiḥ', 'GLGLLGG')
AddSamavrtta('śrīḥ', 'गु')
AddSamavrtta('mātrā', 'GGGLLLLLLGG')
AddSamavrtta('bhogāvalī', 'GGLGLLGLGLLGLLLLLLLGLG')
AddSamavrtta('jihmāśayā', 'GGLGLLLGLLG')
AddSamavrtta('rājarājī', 'GGLGGLG')
AddSamavrtta('kanakakāminī', 'LGLGGLLLGLG')
AddSamavrtta('mayūvadanā', 'GLLLGLLGLGLLGLG')
AddSamavrtta('ānaddham', 'GLGLLLLLGGGLGGG')
AddSamavrtta('mahoddhatā', 'LGGLGLG')
AddArdhasamavrtta('madhuvāri', 'LLGLGLLLGLGLG', 'GGLGLLGLGLLGG')
AddSamavrtta('sukhakārikā', 'LLGLGLLGLGGGG')
AddSamavrtta('kāmoddhatā', 'GGLGGLG')
AddSamavrtta('mṛdukīlā', 'LLGGLG')
AddSamavrtta('ramaṇaḥ', 'LLG')
AddSamavrtta('kareṇuḥ', 'GLGGGG')
AddArdhasamavrtta('camūruḥ', 'LLGLLLLGLGLGG', 'GLGLLLLGLGLG')
AddSamavrtta('khagatiḥ', 'GLLGLLGLLGLLGLLG')
AddSamavrtta('bhogāvaliḥ', 'GGLLLLLLLLGGLLGG')
AddSamavrtta('candrikā', 'LLLLLLGGLGGLG')
AddSamavrtta('nārācam', 'LLLLLLGLGGLGGLGGLG')
AddSamavrtta('śilīmukhojjṛmbhitam', 'GGGLLGLGLLLLLGLGGLG')
AddSamavrtta('kanyā', 'GGGG')
AddSamavrtta('vasumatī', 'GGLLLG')
AddSamavrtta('kalitakamalavilāsaḥ', 'LLLLLLGGGGG')
AddSamavrtta('nīrāntikam', 'GGLGLLLGLLGG')
AddArdhasamavrtta('sārikā', 'GLGLLLGLGLG', 'GLGLLLGLLGG')
AddSamavrtta('manolā', 'LGGLLGGG')
AddSamavrtta('lalitalalāma', 'LLLLGLGGLGGLGGLGGLLLG')
AddSamavrtta('vijayaparicayā', 'LLLLLLGGLLGG')
AddArdhasamavrtta('mṛdumālatī', 'LLLLGLLGLGLG', 'LLLLLLGLGLG')
AddSamavrtta('mandākṣamandaram', 'LLLLLLGGGGGGLGLGLGGGG')
AddSamavrtta('parikhāyatanam', 'LLGLLGLLGGLLLLGG')
AddSamavrtta('śarat', 'LLLGLLGLLG')
AddSamavrtta('yaśaskarī', 'LGLGLGGG')
AddSamavrtta('viśikhalatā', 'LLLLGLGLGGLG')
AddArdhasamavrtta('surāḍhyā', 'LLLLLLGLGLGG', 'GGGLLGLGLGG')
AddSamavrtta('bhāskaram', 'GLLLLLLGLLGGGLLLLLLLLLLGG')
AddSamavrtta('nīhārī', 'GGGGGGG')
AddSamavrtta('rāḍhi', 'GLLGGG')
AddArdhasamavrtta('ālolaghaṭikā', 'LLGLLGLGLG', 'GGLLLGLGLG')
AddSamavrtta('kalā', 'LGLG')
AddSamavrtta('lavalīlatā', 'GLLGLGLLLGLLG')
AddSamavrtta('kāraviṇī', 'GLLLGLGLLLGLLG')
AddSamavrtta('hīram', 'GGLLLLG')
AddSamavrtta('bimbālakṣyam', 'GGGGLGGGLGGLGG')
AddSamavrtta('pārāvāraḥ', 'GGLLLLLLLLGGGG')
AddSamavrtta('praphullakadalī', 'LGLLLGGGGGG')
AddArdhasamavrtta('ayavatī', 'LLGGGGLLLLG', 'GGLLLLGGLLG')
AddSamavrtta('mīnapadī', 'GLLGLGG')
AddSamavrtta('surayānavatī', 'LLGLLGGLLG')
AddSamavrtta('kumbhodhnī', 'GGGGLLLGLLGG')
AddSamavrtta('muśaki', 'GGLLLLG')
AddSamavrtta('bhūmadhārī', 'LGGLGGGG')
AddVishamavrtta('jāyā', 'GGLGGLLGLGG', 'LGLGGLLGLGG', 'LGLGGLLGLGG', 'GGLGGLLGLGG')
AddSamavrtta('vāṇībhūṣā', 'GGGGGGGGLLLLGGG')
AddSamavrtta('virodhinī', 'LLLGLLLLGLGLG')
AddArdhasamavrtta('bhujaṅgabhṛtā', 'LLGLLGLLGLLGG', 'GLLGLLGLLGLLG')
AddSamavrtta('śambaradhārī', 'GLLGGLLGG')
AddSamavrtta('camarīcaram', 'LLLLLLGLGLLLGLG')
AddSamavrtta('vihāriṇī', 'LLGLGLGGLGG')
AddSamavrtta('māyāsārī', 'LLLLGGGGG')
AddArdhasamavrtta('pramodapadam', 'LLLLGLLGLGLLLGG', 'LLLLLLGLGLGLGG')
AddSamavrtta('sudāyi', 'LGLLLG')
AddSamavrtta('kiṁśukāstaraṇam', 'GLGLLGLGGGGG')
AddSamavrtta('phalguḥ', 'LLGGLLLLGGLLLLGGG')
AddSamavrtta('pārāvataḥ', 'GGLGGLGGLGGLG')
AddArdhasamavrtta('atisurahitā', 'GGLLLLLLLLLLG', 'LLLLLLLLGLLGG')
AddSamavrtta('sammadavadanā', 'GLLGLLGLLLLG')
AddSamavrtta('viśālaprabham', 'LGLGGLGGLG')
AddSamavrtta('vanitābharaṇam', 'GLLGLLLLGLLG')
AddSamavrtta('malayasurabhiḥ', 'GGGLLLLLLGGG')
AddSamavrtta('galitanālā', 'LGLGLLLGGGLG')
AddSamavrtta('saurakāntā', 'GLGGLLG')
AddSamavrtta('bhujaṅgavijṛmbhitam', 'GGGGGGGGLLLLLLLLLLGLGLLGLG')
AddSamavrtta('akahari', 'LLLLLLLLLLLLLG')
AddSamavrtta('ardhakṣāmā', 'GGGGGLLGG')
AddSamavrtta('kāsārakrāntā', 'GGGGGLLGLLGG')
AddSamavrtta('tārakam', 'LLGLLGLLGLLGG')
AddSamavrtta('uditadineśaḥ', 'LLGLLLLGGGG')
AddSamavrtta('pratāritā', 'LLGLLLGLGLG')
AddSamavrtta('nardaṭakam', 'LLLLGLGLLLGLLGLLG')
AddSamavrtta('lolam', 'GGLGG')
AddSamavrtta('dṛptadehā', 'LGGGLGGGLGGLGG')
AddSamavrtta('dhaunikam', 'GLLLLLLLG')
AddSamavrtta('pratimā', 'LLGLLGLLGLLGLLGLLGLLG')
AddSamavrtta('parāmodaḥ', 'LGGLLGLLGLGLLLLGGG')
AddSamavrtta('dhoritam', 'GLLLLLGLGGLGLLG')
AddSamavrtta('kharakarā', 'LLLGLGG')
AddSamavrtta('garuḍarutam', 'LLLLGLGLLLGLGGLG')
AddSamavrtta('karabhit', 'LLGLLGG')
AddSamavrtta('sāriṇī', 'GLGLLLGLGLLLGLG')
AddSamavrtta('acaladhṛtiḥ', 'LLLLLLLLLLLLLLLG')
AddSamavrtta('sumukhī', 'LLLLGLLGLLG')
AddArdhasamavrtta('śukāvalī', 'GGLLGLGLGG', 'GGGLLLLGLGLGG')
AddSamavrtta('ītiḥ', 'GLLLGG')
AddSamavrtta('nibhālitā', 'LLGGGLGLG')
AddSamavrtta('śarakalpā', 'LLLLLLLLGLLLLGG')
AddSamavrtta('rathapadam', 'LLLLLLLLGGG')
AddSamavrtta('kacchapī', 'LGGGLG')
AddArdhasamavrtta('bṛhaccharāvatī', 'LLGGLLLLLLGLGLG', 'LLLLLLGLGLGG')
AddSamavrtta('padyā', 'LGLGGGG')
AddSamavrtta('priyatilakā', 'GLLGLLLLG')
AddSamavrtta('sahelikā', 'LGLGLLGLG')
AddSamavrtta('vilāsavāsaḥ', 'GLLLLGGLLGLLLLGLGLGLLGG')
AddSamavrtta('mugdham', 'GGGG')
AddSamavrtta('kaṇṭhī', 'LGLGG')
AddSamavrtta('cāmaram', 'GLGLGLG')
AddSamavrtta('kaṁsāsāri', 'LGGGGGG')
AddSamavrtta('methikā', 'GLGLLGG')
AddSamavrtta('paṅktiḥ', 'GLLGG')
AddSamavrtta('hemamihikā', 'GLLLGLLGLGLLGG')
AddSamavrtta('śuddhāntam', 'LLLLLLLLGGGG')
AddArdhasamavrtta('vilāsavāpī', 'GGLLGLGLGG', 'LLGGLLGLGLGLGG')
AddArdhasamavrtta('navanīlatā', 'LLGLLGLGLG', 'LLGGLLLGLGLG')
AddSamavrtta('upalekhā', 'LLGGLLLLLGLG')
AddSamavrtta('kālasāroddhataḥ', 'LGLGGLLGLLLGLGGLG')
AddSamavrtta('carapadam', 'LLLGGLGGLG')
AddSamavrtta('maṇimukhī', 'LLLGLGG')
AddSamavrtta('śilā', 'LGLLG')
AddSamavrtta('ṛṣabhagajavilasitam', 'GLLGLGLLLLLLLLLG')
AddVishamavrtta('puṣṭidā', 'GGLGGLLGLGLG', 'GGLGGLLGLGLG', 'LGLGGLLGLGLG', 'GGLGGLLGLGLG')
AddSamavrtta('sukhelā', 'LLGLGLGLGG')
AddArdhasamavrtta('añcitāgrā', 'LLLLGLLGLGLGG', 'LLLLLLGLGLGG')
AddSamavrtta('virahavirahasyam', 'GGGLLLLLLGGLLGGLLLLLLLLGG')
AddSamavrtta('meghavisphūrjitā', 'LGGGGGLLLLLGGLGGLGG')
AddSamavrtta('kākiṇikā', 'LGLLGLGLLLGLLG')
AddSamavrtta('hariṇaplutam', 'GGGLLGLGLLGLGLLGLG')
AddSamavrtta('kandavinodaḥ', 'GLLGGGLLGGG')
AddSamavrtta('māṇavikāvikāṣaḥ', 'GGLGLLGLLGLGG')
AddArdhasamavrtta('śarāvatī', 'LLLLLLGLGLGG', 'LLGGLLLLLLGLGLG')
AddSamavrtta('krīḍitakaṭakā', 'GLLLLGLLGGGGGGG')
AddSamavrtta('senikā', 'GLGLGLGLGLG')
AddSamavrtta('surākṣī', 'LLLLGGLGGG')
AddSamavrtta('kaṅkaṇakvāṇavāṇī', 'GGGGLGGLGGLGGLGGLGGLGG')
AddSamavrtta('varmitā', 'GLGLGLLGLG')
AddSamavrtta('kusumbhinī', 'LGLGLLLLGLGLGG')
AddSamavrtta('baladhārī', 'LLGGLLLLGG')
AddSamavrtta('pratīhāraḥ', 'GLGGLGGLGGLGGLGGG')
AddSamavrtta('prapātaḥ', 'LGGLGGLGGLGGLG')
AddSamavrtta('upahitacaṇḍī', 'LLGGLLLLGGG')
AddSamavrtta('maṇimadhyam', 'GLLGGGLLG')
AddSamavrtta('madhyādhārā', 'GGGGLLGGGG')
AddSamavrtta('tūṇakam', 'GLGLGLGLGLGLGLG')
AddSamavrtta('tanukilakiñcitam', 'GGGGGGGGGLLLLGLLLLGGLLGGGG')
AddSamavrtta('acalaviratiḥ', 'LLLLLLLLLLLLLLLLLLLLLG')
AddSamavrtta('vanitāvinodi', 'LLLGLLGLGG')
AddSamavrtta('dhavalam', 'LLLLLLLLLLLLLLLLLLG')
AddSamavrtta('paripoṣakam', 'LLGLLGLLGLLGLLGLLG')
AddSamavrtta('nīlā', 'GGLLLLGLGLG')
AddSamavrtta('khaurali', 'LLLLGGGGLG')

METRES_KV.length = 0
Object.entries(METRES).forEach(m => METRES_KV.push(m))
